//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnhancementCRM.HelperUnit.ZPST_CRM_BOM_COMPONENT_PRICE {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", ConfigurationName="ZPST_CRM_BOM_COMPONENT_PRICE.ZPST_FM_006_v2")]
    public interface ZPST_FM_006_v2 {
        
        // CODEGEN: Generating message contract since the operation ZPST_FM_006 is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="urn:sap-com:document:sap:rfc:functions:ZPST_FM_006_v2:ZPST_FM_006Request", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        EnhancementCRM.HelperUnit.ZPST_CRM_BOM_COMPONENT_PRICE.ZPST_FM_006Response1 ZPST_FM_006(EnhancementCRM.HelperUnit.ZPST_CRM_BOM_COMPONENT_PRICE.ZPST_FM_006Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:sap-com:document:sap:rfc:functions:ZPST_FM_006_v2:ZPST_FM_006Request", ReplyAction="*")]
        System.Threading.Tasks.Task<EnhancementCRM.HelperUnit.ZPST_CRM_BOM_COMPONENT_PRICE.ZPST_FM_006Response1> ZPST_FM_006Async(EnhancementCRM.HelperUnit.ZPST_CRM_BOM_COMPONENT_PRICE.ZPST_FM_006Request request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZPST_FM_006 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string cSRF_TOKENField;
        
        private string mATNRField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string CSRF_TOKEN {
            get {
                return this.cSRF_TOKENField;
            }
            set {
                this.cSRF_TOKENField = value;
                this.RaisePropertyChanged("CSRF_TOKEN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string MATNR {
            get {
                return this.mATNRField;
            }
            set {
                this.mATNRField = value;
                this.RaisePropertyChanged("MATNR");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZPST_FM_006Response : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long aMOUNTField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long AMOUNT {
            get {
                return this.aMOUNTField;
            }
            set {
                this.aMOUNTField = value;
                this.RaisePropertyChanged("AMOUNT");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZPST_FM_006Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public EnhancementCRM.HelperUnit.ZPST_CRM_BOM_COMPONENT_PRICE.ZPST_FM_006 ZPST_FM_006;
        
        public ZPST_FM_006Request() {
        }
        
        public ZPST_FM_006Request(EnhancementCRM.HelperUnit.ZPST_CRM_BOM_COMPONENT_PRICE.ZPST_FM_006 ZPST_FM_006) {
            this.ZPST_FM_006 = ZPST_FM_006;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZPST_FM_006Response1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public EnhancementCRM.HelperUnit.ZPST_CRM_BOM_COMPONENT_PRICE.ZPST_FM_006Response ZPST_FM_006Response;
        
        public ZPST_FM_006Response1() {
        }
        
        public ZPST_FM_006Response1(EnhancementCRM.HelperUnit.ZPST_CRM_BOM_COMPONENT_PRICE.ZPST_FM_006Response ZPST_FM_006Response) {
            this.ZPST_FM_006Response = ZPST_FM_006Response;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ZPST_FM_006_v2Channel : EnhancementCRM.HelperUnit.ZPST_CRM_BOM_COMPONENT_PRICE.ZPST_FM_006_v2, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ZPST_FM_006_v2Client : System.ServiceModel.ClientBase<EnhancementCRM.HelperUnit.ZPST_CRM_BOM_COMPONENT_PRICE.ZPST_FM_006_v2>, EnhancementCRM.HelperUnit.ZPST_CRM_BOM_COMPONENT_PRICE.ZPST_FM_006_v2 {
        
        public ZPST_FM_006_v2Client() {
        }
        
        public ZPST_FM_006_v2Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ZPST_FM_006_v2Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ZPST_FM_006_v2Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ZPST_FM_006_v2Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EnhancementCRM.HelperUnit.ZPST_CRM_BOM_COMPONENT_PRICE.ZPST_FM_006Response1 EnhancementCRM.HelperUnit.ZPST_CRM_BOM_COMPONENT_PRICE.ZPST_FM_006_v2.ZPST_FM_006(EnhancementCRM.HelperUnit.ZPST_CRM_BOM_COMPONENT_PRICE.ZPST_FM_006Request request) {
            return base.Channel.ZPST_FM_006(request);
        }
        
        public EnhancementCRM.HelperUnit.ZPST_CRM_BOM_COMPONENT_PRICE.ZPST_FM_006Response ZPST_FM_006(EnhancementCRM.HelperUnit.ZPST_CRM_BOM_COMPONENT_PRICE.ZPST_FM_006 ZPST_FM_0061) {
            EnhancementCRM.HelperUnit.ZPST_CRM_BOM_COMPONENT_PRICE.ZPST_FM_006Request inValue = new EnhancementCRM.HelperUnit.ZPST_CRM_BOM_COMPONENT_PRICE.ZPST_FM_006Request();
            inValue.ZPST_FM_006 = ZPST_FM_0061;
            EnhancementCRM.HelperUnit.ZPST_CRM_BOM_COMPONENT_PRICE.ZPST_FM_006Response1 retVal = ((EnhancementCRM.HelperUnit.ZPST_CRM_BOM_COMPONENT_PRICE.ZPST_FM_006_v2)(this)).ZPST_FM_006(inValue);
            return retVal.ZPST_FM_006Response;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EnhancementCRM.HelperUnit.ZPST_CRM_BOM_COMPONENT_PRICE.ZPST_FM_006Response1> EnhancementCRM.HelperUnit.ZPST_CRM_BOM_COMPONENT_PRICE.ZPST_FM_006_v2.ZPST_FM_006Async(EnhancementCRM.HelperUnit.ZPST_CRM_BOM_COMPONENT_PRICE.ZPST_FM_006Request request) {
            return base.Channel.ZPST_FM_006Async(request);
        }
        
        public System.Threading.Tasks.Task<EnhancementCRM.HelperUnit.ZPST_CRM_BOM_COMPONENT_PRICE.ZPST_FM_006Response1> ZPST_FM_006Async(EnhancementCRM.HelperUnit.ZPST_CRM_BOM_COMPONENT_PRICE.ZPST_FM_006 ZPST_FM_006) {
            EnhancementCRM.HelperUnit.ZPST_CRM_BOM_COMPONENT_PRICE.ZPST_FM_006Request inValue = new EnhancementCRM.HelperUnit.ZPST_CRM_BOM_COMPONENT_PRICE.ZPST_FM_006Request();
            inValue.ZPST_FM_006 = ZPST_FM_006;
            return ((EnhancementCRM.HelperUnit.ZPST_CRM_BOM_COMPONENT_PRICE.ZPST_FM_006_v2)(this)).ZPST_FM_006Async(inValue);
        }
    }
}
