//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnhancementCRM.HelperUnit.WebServiceUnitSAP {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", ConfigurationName="WebServiceUnitSAP.ZWEB_SERVICES_UNIT")]
    public interface ZWEB_SERVICES_UNIT {
        
        // CODEGEN: Generating message contract since the operation ZcrmCreateSoUnit is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="urn:sap-com:document:sap:soap:functions:mc-style:ZWEB_SERVICES_UNIT:ZcrmCreateSoU" +
            "nitRequest", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        EnhancementCRM.HelperUnit.WebServiceUnitSAP.ZcrmCreateSoUnitResponse1 ZcrmCreateSoUnit(EnhancementCRM.HelperUnit.WebServiceUnitSAP.ZcrmCreateSoUnitRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:sap-com:document:sap:soap:functions:mc-style:ZWEB_SERVICES_UNIT:ZcrmCreateSoU" +
            "nitRequest", ReplyAction="*")]
        System.Threading.Tasks.Task<EnhancementCRM.HelperUnit.WebServiceUnitSAP.ZcrmCreateSoUnitResponse1> ZcrmCreateSoUnitAsync(EnhancementCRM.HelperUnit.WebServiceUnitSAP.ZcrmCreateSoUnitRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZcrmCreateSoUnit : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string csrfTokenField;
        
        private ZtsoUnitTxt[] tDetailField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string CsrfToken {
            get {
                return this.csrfTokenField;
            }
            set {
                this.csrfTokenField = value;
                this.RaisePropertyChanged("CsrfToken");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZtsoUnitTxt[] TDetail {
            get {
                return this.tDetailField;
            }
            set {
                this.tDetailField = value;
                this.RaisePropertyChanged("TDetail");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZtsoUnitTxt : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string bstkdField;
        
        private string auartField;
        
        private string audatField;
        
        private string vtwegField;
        
        private string vkorgField;
        
        private string spartField;
        
        private string vkburField;
        
        private string kunnrField;
        
        private string fkdat09Field;
        
        private string fakwr09Field;
        
        private string fkdat10Field;
        
        private string fakwr10Field;
        
        private string fkdat20Field;
        
        private string fakwr20Field;
        
        private string bstkdCustField;
        
        private string bstdkField;
        
        private string waerkField;
        
        private string ztermField;
        
        private string werksField;
        
        private string pernrField;
        
        private string ktgrdField;
        
        private string kdgrpField;
        
        private string pltypField;
        
        private string kondaField;
        
        private string vkgrpField;
        
        private string kvgr1Field;
        
        private string kvgr2Field;
        
        private string kvgr3Field;
        
        private string kvgr4Field;
        
        private string kvgr5Field;
        
        private string txhzfu01Field;
        
        private string txhzfu02Field;
        
        private string txhzfu03Field;
        
        private string txhzfu04Field;
        
        private string txhzfu05Field;
        
        private string txhzfu06Field;
        
        private string txhzfu07Field;
        
        private string txhzfu08Field;
        
        private string txhzfu09Field;
        
        private string txhzfu10Field;
        
        private string posnrField;
        
        private string matnrField;
        
        private string kwmengField;
        
        private string kbetrField;
        
        private string txizfu01Field;
        
        private string leasingField;
        
        private string flagField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Bstkd {
            get {
                return this.bstkdField;
            }
            set {
                this.bstkdField = value;
                this.RaisePropertyChanged("Bstkd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Auart {
            get {
                return this.auartField;
            }
            set {
                this.auartField = value;
                this.RaisePropertyChanged("Auart");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Audat {
            get {
                return this.audatField;
            }
            set {
                this.audatField = value;
                this.RaisePropertyChanged("Audat");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string Vtweg {
            get {
                return this.vtwegField;
            }
            set {
                this.vtwegField = value;
                this.RaisePropertyChanged("Vtweg");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string Vkorg {
            get {
                return this.vkorgField;
            }
            set {
                this.vkorgField = value;
                this.RaisePropertyChanged("Vkorg");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string Spart {
            get {
                return this.spartField;
            }
            set {
                this.spartField = value;
                this.RaisePropertyChanged("Spart");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string Vkbur {
            get {
                return this.vkburField;
            }
            set {
                this.vkburField = value;
                this.RaisePropertyChanged("Vkbur");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string Kunnr {
            get {
                return this.kunnrField;
            }
            set {
                this.kunnrField = value;
                this.RaisePropertyChanged("Kunnr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string Fkdat09 {
            get {
                return this.fkdat09Field;
            }
            set {
                this.fkdat09Field = value;
                this.RaisePropertyChanged("Fkdat09");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string Fakwr09 {
            get {
                return this.fakwr09Field;
            }
            set {
                this.fakwr09Field = value;
                this.RaisePropertyChanged("Fakwr09");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string Fkdat10 {
            get {
                return this.fkdat10Field;
            }
            set {
                this.fkdat10Field = value;
                this.RaisePropertyChanged("Fkdat10");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string Fakwr10 {
            get {
                return this.fakwr10Field;
            }
            set {
                this.fakwr10Field = value;
                this.RaisePropertyChanged("Fakwr10");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string Fkdat20 {
            get {
                return this.fkdat20Field;
            }
            set {
                this.fkdat20Field = value;
                this.RaisePropertyChanged("Fkdat20");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string Fakwr20 {
            get {
                return this.fakwr20Field;
            }
            set {
                this.fakwr20Field = value;
                this.RaisePropertyChanged("Fakwr20");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string BstkdCust {
            get {
                return this.bstkdCustField;
            }
            set {
                this.bstkdCustField = value;
                this.RaisePropertyChanged("BstkdCust");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string Bstdk {
            get {
                return this.bstdkField;
            }
            set {
                this.bstdkField = value;
                this.RaisePropertyChanged("Bstdk");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public string Waerk {
            get {
                return this.waerkField;
            }
            set {
                this.waerkField = value;
                this.RaisePropertyChanged("Waerk");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public string Zterm {
            get {
                return this.ztermField;
            }
            set {
                this.ztermField = value;
                this.RaisePropertyChanged("Zterm");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public string Werks {
            get {
                return this.werksField;
            }
            set {
                this.werksField = value;
                this.RaisePropertyChanged("Werks");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
        public string Pernr {
            get {
                return this.pernrField;
            }
            set {
                this.pernrField = value;
                this.RaisePropertyChanged("Pernr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=20)]
        public string Ktgrd {
            get {
                return this.ktgrdField;
            }
            set {
                this.ktgrdField = value;
                this.RaisePropertyChanged("Ktgrd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=21)]
        public string Kdgrp {
            get {
                return this.kdgrpField;
            }
            set {
                this.kdgrpField = value;
                this.RaisePropertyChanged("Kdgrp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=22)]
        public string Pltyp {
            get {
                return this.pltypField;
            }
            set {
                this.pltypField = value;
                this.RaisePropertyChanged("Pltyp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=23)]
        public string Konda {
            get {
                return this.kondaField;
            }
            set {
                this.kondaField = value;
                this.RaisePropertyChanged("Konda");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=24)]
        public string Vkgrp {
            get {
                return this.vkgrpField;
            }
            set {
                this.vkgrpField = value;
                this.RaisePropertyChanged("Vkgrp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=25)]
        public string Kvgr1 {
            get {
                return this.kvgr1Field;
            }
            set {
                this.kvgr1Field = value;
                this.RaisePropertyChanged("Kvgr1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=26)]
        public string Kvgr2 {
            get {
                return this.kvgr2Field;
            }
            set {
                this.kvgr2Field = value;
                this.RaisePropertyChanged("Kvgr2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=27)]
        public string Kvgr3 {
            get {
                return this.kvgr3Field;
            }
            set {
                this.kvgr3Field = value;
                this.RaisePropertyChanged("Kvgr3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=28)]
        public string Kvgr4 {
            get {
                return this.kvgr4Field;
            }
            set {
                this.kvgr4Field = value;
                this.RaisePropertyChanged("Kvgr4");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=29)]
        public string Kvgr5 {
            get {
                return this.kvgr5Field;
            }
            set {
                this.kvgr5Field = value;
                this.RaisePropertyChanged("Kvgr5");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=30)]
        public string Txhzfu01 {
            get {
                return this.txhzfu01Field;
            }
            set {
                this.txhzfu01Field = value;
                this.RaisePropertyChanged("Txhzfu01");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=31)]
        public string Txhzfu02 {
            get {
                return this.txhzfu02Field;
            }
            set {
                this.txhzfu02Field = value;
                this.RaisePropertyChanged("Txhzfu02");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=32)]
        public string Txhzfu03 {
            get {
                return this.txhzfu03Field;
            }
            set {
                this.txhzfu03Field = value;
                this.RaisePropertyChanged("Txhzfu03");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=33)]
        public string Txhzfu04 {
            get {
                return this.txhzfu04Field;
            }
            set {
                this.txhzfu04Field = value;
                this.RaisePropertyChanged("Txhzfu04");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=34)]
        public string Txhzfu05 {
            get {
                return this.txhzfu05Field;
            }
            set {
                this.txhzfu05Field = value;
                this.RaisePropertyChanged("Txhzfu05");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=35)]
        public string Txhzfu06 {
            get {
                return this.txhzfu06Field;
            }
            set {
                this.txhzfu06Field = value;
                this.RaisePropertyChanged("Txhzfu06");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=36)]
        public string Txhzfu07 {
            get {
                return this.txhzfu07Field;
            }
            set {
                this.txhzfu07Field = value;
                this.RaisePropertyChanged("Txhzfu07");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=37)]
        public string Txhzfu08 {
            get {
                return this.txhzfu08Field;
            }
            set {
                this.txhzfu08Field = value;
                this.RaisePropertyChanged("Txhzfu08");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=38)]
        public string Txhzfu09 {
            get {
                return this.txhzfu09Field;
            }
            set {
                this.txhzfu09Field = value;
                this.RaisePropertyChanged("Txhzfu09");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=39)]
        public string Txhzfu10 {
            get {
                return this.txhzfu10Field;
            }
            set {
                this.txhzfu10Field = value;
                this.RaisePropertyChanged("Txhzfu10");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=40)]
        public string Posnr {
            get {
                return this.posnrField;
            }
            set {
                this.posnrField = value;
                this.RaisePropertyChanged("Posnr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=41)]
        public string Matnr {
            get {
                return this.matnrField;
            }
            set {
                this.matnrField = value;
                this.RaisePropertyChanged("Matnr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=42)]
        public string Kwmeng {
            get {
                return this.kwmengField;
            }
            set {
                this.kwmengField = value;
                this.RaisePropertyChanged("Kwmeng");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=43)]
        public string Kbetr {
            get {
                return this.kbetrField;
            }
            set {
                this.kbetrField = value;
                this.RaisePropertyChanged("Kbetr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=44)]
        public string Txizfu01 {
            get {
                return this.txizfu01Field;
            }
            set {
                this.txizfu01Field = value;
                this.RaisePropertyChanged("Txizfu01");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=45)]
        public string Leasing {
            get {
                return this.leasingField;
            }
            set {
                this.leasingField = value;
                this.RaisePropertyChanged("Leasing");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=46)]
        public string Flag {
            get {
                return this.flagField;
            }
            set {
                this.flagField = value;
                this.RaisePropertyChanged("Flag");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZtsoUnitOut : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string bstkdField;
        
        private string vbelnField;
        
        private string posnrField;
        
        private string itemCpoField;
        
        private string erdatField;
        
        private string resultField;
        
        private string descriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Bstkd {
            get {
                return this.bstkdField;
            }
            set {
                this.bstkdField = value;
                this.RaisePropertyChanged("Bstkd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Vbeln {
            get {
                return this.vbelnField;
            }
            set {
                this.vbelnField = value;
                this.RaisePropertyChanged("Vbeln");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Posnr {
            get {
                return this.posnrField;
            }
            set {
                this.posnrField = value;
                this.RaisePropertyChanged("Posnr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string ItemCpo {
            get {
                return this.itemCpoField;
            }
            set {
                this.itemCpoField = value;
                this.RaisePropertyChanged("ItemCpo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string Erdat {
            get {
                return this.erdatField;
            }
            set {
                this.erdatField = value;
                this.RaisePropertyChanged("Erdat");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string Result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("Result");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZcrmCreateSoUnitResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string syncDateField;
        
        private System.DateTime syncTimeField;
        
        private ZtsoUnitOut[] tDtlOutField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string SyncDate {
            get {
                return this.syncDateField;
            }
            set {
                this.syncDateField = value;
                this.RaisePropertyChanged("SyncDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="time", Order=1)]
        public System.DateTime SyncTime {
            get {
                return this.syncTimeField;
            }
            set {
                this.syncTimeField = value;
                this.RaisePropertyChanged("SyncTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZtsoUnitOut[] TDtlOut {
            get {
                return this.tDtlOutField;
            }
            set {
                this.tDtlOutField = value;
                this.RaisePropertyChanged("TDtlOut");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZcrmCreateSoUnitRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", Order=0)]
        public EnhancementCRM.HelperUnit.WebServiceUnitSAP.ZcrmCreateSoUnit ZcrmCreateSoUnit;
        
        public ZcrmCreateSoUnitRequest() {
        }
        
        public ZcrmCreateSoUnitRequest(EnhancementCRM.HelperUnit.WebServiceUnitSAP.ZcrmCreateSoUnit ZcrmCreateSoUnit) {
            this.ZcrmCreateSoUnit = ZcrmCreateSoUnit;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZcrmCreateSoUnitResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", Order=0)]
        public EnhancementCRM.HelperUnit.WebServiceUnitSAP.ZcrmCreateSoUnitResponse ZcrmCreateSoUnitResponse;
        
        public ZcrmCreateSoUnitResponse1() {
        }
        
        public ZcrmCreateSoUnitResponse1(EnhancementCRM.HelperUnit.WebServiceUnitSAP.ZcrmCreateSoUnitResponse ZcrmCreateSoUnitResponse) {
            this.ZcrmCreateSoUnitResponse = ZcrmCreateSoUnitResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ZWEB_SERVICES_UNITChannel : EnhancementCRM.HelperUnit.WebServiceUnitSAP.ZWEB_SERVICES_UNIT, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ZWEB_SERVICES_UNITClient : System.ServiceModel.ClientBase<EnhancementCRM.HelperUnit.WebServiceUnitSAP.ZWEB_SERVICES_UNIT>, EnhancementCRM.HelperUnit.WebServiceUnitSAP.ZWEB_SERVICES_UNIT {
        
        public ZWEB_SERVICES_UNITClient() {
        }
        
        public ZWEB_SERVICES_UNITClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ZWEB_SERVICES_UNITClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ZWEB_SERVICES_UNITClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ZWEB_SERVICES_UNITClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EnhancementCRM.HelperUnit.WebServiceUnitSAP.ZcrmCreateSoUnitResponse1 EnhancementCRM.HelperUnit.WebServiceUnitSAP.ZWEB_SERVICES_UNIT.ZcrmCreateSoUnit(EnhancementCRM.HelperUnit.WebServiceUnitSAP.ZcrmCreateSoUnitRequest request) {
            return base.Channel.ZcrmCreateSoUnit(request);
        }
        
        public EnhancementCRM.HelperUnit.WebServiceUnitSAP.ZcrmCreateSoUnitResponse ZcrmCreateSoUnit(EnhancementCRM.HelperUnit.WebServiceUnitSAP.ZcrmCreateSoUnit ZcrmCreateSoUnit1) {
            EnhancementCRM.HelperUnit.WebServiceUnitSAP.ZcrmCreateSoUnitRequest inValue = new EnhancementCRM.HelperUnit.WebServiceUnitSAP.ZcrmCreateSoUnitRequest();
            inValue.ZcrmCreateSoUnit = ZcrmCreateSoUnit1;
            EnhancementCRM.HelperUnit.WebServiceUnitSAP.ZcrmCreateSoUnitResponse1 retVal = ((EnhancementCRM.HelperUnit.WebServiceUnitSAP.ZWEB_SERVICES_UNIT)(this)).ZcrmCreateSoUnit(inValue);
            return retVal.ZcrmCreateSoUnitResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EnhancementCRM.HelperUnit.WebServiceUnitSAP.ZcrmCreateSoUnitResponse1> EnhancementCRM.HelperUnit.WebServiceUnitSAP.ZWEB_SERVICES_UNIT.ZcrmCreateSoUnitAsync(EnhancementCRM.HelperUnit.WebServiceUnitSAP.ZcrmCreateSoUnitRequest request) {
            return base.Channel.ZcrmCreateSoUnitAsync(request);
        }
        
        public System.Threading.Tasks.Task<EnhancementCRM.HelperUnit.WebServiceUnitSAP.ZcrmCreateSoUnitResponse1> ZcrmCreateSoUnitAsync(EnhancementCRM.HelperUnit.WebServiceUnitSAP.ZcrmCreateSoUnit ZcrmCreateSoUnit) {
            EnhancementCRM.HelperUnit.WebServiceUnitSAP.ZcrmCreateSoUnitRequest inValue = new EnhancementCRM.HelperUnit.WebServiceUnitSAP.ZcrmCreateSoUnitRequest();
            inValue.ZcrmCreateSoUnit = ZcrmCreateSoUnit;
            return ((EnhancementCRM.HelperUnit.WebServiceUnitSAP.ZWEB_SERVICES_UNIT)(this)).ZcrmCreateSoUnitAsync(inValue);
        }
    }
}
