// <copyright file="PostSalesOrderPartLinesCreate.cs" company="">
// Copyright (c) 2018 All Rights Reserved
// </copyright>
// <author></author>
// <date>1/22/2018 8:42:04 PM</date>
// <summary>Implements the PostSalesOrderPartLinesCreate Plugin.</summary>
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
// </auto-generated>
namespace TrakNusSparepartSystem.Plugins
{
    using System;
    using System.ServiceModel;
    using Microsoft.Xrm.Sdk;
    using TrakNusSparepartSystem.Plugins.BusinessLayer;

    /// <summary>
    /// PostSalesOrderPartLinesCreate Plugin.
    /// </summary>    
    public class PostSalesOrderPartLinesCreate: Plugin
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PostSalesOrderPartLinesCreate"/> class.
        /// </summary>
        public PostSalesOrderPartLinesCreate()
            : base(typeof(PostSalesOrderPartLinesCreate))
        {
            base.RegisteredEvents.Add(new Tuple<int, string, string, Action<LocalPluginContext>>(40, "Create", "tss_sopartlines", new Action<LocalPluginContext>(ExecutePostSalesOrderPartLinesCreate)));

            // Note : you can register for more events here if this plugin is not specific to an individual entity and message combination.
            // You may also need to update your RegisterFile.crmregister plug-in registration file to reflect any change.
        }

        /// <summary>
        /// Executes the plug-in.
        /// </summary>
        /// <param name="localContext">The <see cref="LocalPluginContext"/> which contains the
        /// <see cref="IPluginExecutionContext"/>,
        /// <see cref="IOrganizationService"/>
        /// and <see cref="ITracingService"/>
        /// </param>
        /// <remarks>
        /// For improved performance, Microsoft Dynamics CRM caches plug-in instances.
        /// The plug-in's Execute method should be written to be stateless as the constructor
        /// is not called for every invocation of the plug-in. Also, multiple system threads
        /// could execute the plug-in at the same time. All per invocation state information
        /// is stored in the context. This means that you should not use global variables in plug-ins.
        /// </remarks>
        protected void ExecutePostSalesOrderPartLinesCreate(LocalPluginContext localContext)
        {
            if (localContext == null)
            {
                throw new ArgumentNullException("localContext");
            }
            IPluginExecutionContext context = localContext.PluginExecutionContext;
            BL_tss_salesorderpartlines _BL_tss_salesorderpartlines = new BL_tss_salesorderpartlines();
            _BL_tss_salesorderpartlines.Form_OnCreate_PostOperation(localContext.OrganizationService, localContext.PluginExecutionContext);
            // TODO: Implement your custom Plug-in business logic.
        }
    }
}
