//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnhancementCRM.HelperUnit.ZCRM_UPDATE_WARRANTY_DATE {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", ConfigurationName="ZCRM_UPDATE_WARRANTY_DATE.ZWS_WARRANTY_DATE_V3")]
    public interface ZWS_WARRANTY_DATE_V3 {
        
        // CODEGEN: Generating message contract since the operation ZCRM_UPDATE_WARRANTY_DATE is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="urn:sap-com:document:sap:rfc:functions:ZWS_WARRANTY_DATE_V3:ZCRM_UPDATE_WARRANTY_" +
            "DATERequest", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        EnhancementCRM.HelperUnit.ZCRM_UPDATE_WARRANTY_DATE.ZCRM_UPDATE_WARRANTY_DATEResponse1 ZCRM_UPDATE_WARRANTY_DATE(EnhancementCRM.HelperUnit.ZCRM_UPDATE_WARRANTY_DATE.ZCRM_UPDATE_WARRANTY_DATERequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:sap-com:document:sap:rfc:functions:ZWS_WARRANTY_DATE_V3:ZCRM_UPDATE_WARRANTY_" +
            "DATERequest", ReplyAction="*")]
        System.Threading.Tasks.Task<EnhancementCRM.HelperUnit.ZCRM_UPDATE_WARRANTY_DATE.ZCRM_UPDATE_WARRANTY_DATEResponse1> ZCRM_UPDATE_WARRANTY_DATEAsync(EnhancementCRM.HelperUnit.ZCRM_UPDATE_WARRANTY_DATE.ZCRM_UPDATE_WARRANTY_DATERequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZCRM_UPDATE_WARRANTY_DATE : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string cSRF_TOKENField;
        
        private string i_EQUNRField;
        
        private string i_GWLDTField;
        
        private string i_GWLENField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string CSRF_TOKEN {
            get {
                return this.cSRF_TOKENField;
            }
            set {
                this.cSRF_TOKENField = value;
                this.RaisePropertyChanged("CSRF_TOKEN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string I_EQUNR {
            get {
                return this.i_EQUNRField;
            }
            set {
                this.i_EQUNRField = value;
                this.RaisePropertyChanged("I_EQUNR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string I_GWLDT {
            get {
                return this.i_GWLDTField;
            }
            set {
                this.i_GWLDTField = value;
                this.RaisePropertyChanged("I_GWLDT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string I_GWLEN {
            get {
                return this.i_GWLENField;
            }
            set {
                this.i_GWLENField = value;
                this.RaisePropertyChanged("I_GWLEN");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZCRM_UPDATE_WARRANTY_DATEResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string dESCRIPTIONField;
        
        private string rESULTField;
        
        private string sYNC_DATEField;
        
        private System.DateTime sYNC_TIMEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string DESCRIPTION {
            get {
                return this.dESCRIPTIONField;
            }
            set {
                this.dESCRIPTIONField = value;
                this.RaisePropertyChanged("DESCRIPTION");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string RESULT {
            get {
                return this.rESULTField;
            }
            set {
                this.rESULTField = value;
                this.RaisePropertyChanged("RESULT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string SYNC_DATE {
            get {
                return this.sYNC_DATEField;
            }
            set {
                this.sYNC_DATEField = value;
                this.RaisePropertyChanged("SYNC_DATE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="time", Order=3)]
        public System.DateTime SYNC_TIME {
            get {
                return this.sYNC_TIMEField;
            }
            set {
                this.sYNC_TIMEField = value;
                this.RaisePropertyChanged("SYNC_TIME");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZCRM_UPDATE_WARRANTY_DATERequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public EnhancementCRM.HelperUnit.ZCRM_UPDATE_WARRANTY_DATE.ZCRM_UPDATE_WARRANTY_DATE ZCRM_UPDATE_WARRANTY_DATE;
        
        public ZCRM_UPDATE_WARRANTY_DATERequest() {
        }
        
        public ZCRM_UPDATE_WARRANTY_DATERequest(EnhancementCRM.HelperUnit.ZCRM_UPDATE_WARRANTY_DATE.ZCRM_UPDATE_WARRANTY_DATE ZCRM_UPDATE_WARRANTY_DATE) {
            this.ZCRM_UPDATE_WARRANTY_DATE = ZCRM_UPDATE_WARRANTY_DATE;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZCRM_UPDATE_WARRANTY_DATEResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public EnhancementCRM.HelperUnit.ZCRM_UPDATE_WARRANTY_DATE.ZCRM_UPDATE_WARRANTY_DATEResponse ZCRM_UPDATE_WARRANTY_DATEResponse;
        
        public ZCRM_UPDATE_WARRANTY_DATEResponse1() {
        }
        
        public ZCRM_UPDATE_WARRANTY_DATEResponse1(EnhancementCRM.HelperUnit.ZCRM_UPDATE_WARRANTY_DATE.ZCRM_UPDATE_WARRANTY_DATEResponse ZCRM_UPDATE_WARRANTY_DATEResponse) {
            this.ZCRM_UPDATE_WARRANTY_DATEResponse = ZCRM_UPDATE_WARRANTY_DATEResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ZWS_WARRANTY_DATE_V3Channel : EnhancementCRM.HelperUnit.ZCRM_UPDATE_WARRANTY_DATE.ZWS_WARRANTY_DATE_V3, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ZWS_WARRANTY_DATE_V3Client : System.ServiceModel.ClientBase<EnhancementCRM.HelperUnit.ZCRM_UPDATE_WARRANTY_DATE.ZWS_WARRANTY_DATE_V3>, EnhancementCRM.HelperUnit.ZCRM_UPDATE_WARRANTY_DATE.ZWS_WARRANTY_DATE_V3 {
        
        public ZWS_WARRANTY_DATE_V3Client() {
        }
        
        public ZWS_WARRANTY_DATE_V3Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ZWS_WARRANTY_DATE_V3Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ZWS_WARRANTY_DATE_V3Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ZWS_WARRANTY_DATE_V3Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EnhancementCRM.HelperUnit.ZCRM_UPDATE_WARRANTY_DATE.ZCRM_UPDATE_WARRANTY_DATEResponse1 EnhancementCRM.HelperUnit.ZCRM_UPDATE_WARRANTY_DATE.ZWS_WARRANTY_DATE_V3.ZCRM_UPDATE_WARRANTY_DATE(EnhancementCRM.HelperUnit.ZCRM_UPDATE_WARRANTY_DATE.ZCRM_UPDATE_WARRANTY_DATERequest request) {
            return base.Channel.ZCRM_UPDATE_WARRANTY_DATE(request);
        }
        
        public EnhancementCRM.HelperUnit.ZCRM_UPDATE_WARRANTY_DATE.ZCRM_UPDATE_WARRANTY_DATEResponse ZCRM_UPDATE_WARRANTY_DATE(EnhancementCRM.HelperUnit.ZCRM_UPDATE_WARRANTY_DATE.ZCRM_UPDATE_WARRANTY_DATE ZCRM_UPDATE_WARRANTY_DATE1) {
            EnhancementCRM.HelperUnit.ZCRM_UPDATE_WARRANTY_DATE.ZCRM_UPDATE_WARRANTY_DATERequest inValue = new EnhancementCRM.HelperUnit.ZCRM_UPDATE_WARRANTY_DATE.ZCRM_UPDATE_WARRANTY_DATERequest();
            inValue.ZCRM_UPDATE_WARRANTY_DATE = ZCRM_UPDATE_WARRANTY_DATE1;
            EnhancementCRM.HelperUnit.ZCRM_UPDATE_WARRANTY_DATE.ZCRM_UPDATE_WARRANTY_DATEResponse1 retVal = ((EnhancementCRM.HelperUnit.ZCRM_UPDATE_WARRANTY_DATE.ZWS_WARRANTY_DATE_V3)(this)).ZCRM_UPDATE_WARRANTY_DATE(inValue);
            return retVal.ZCRM_UPDATE_WARRANTY_DATEResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EnhancementCRM.HelperUnit.ZCRM_UPDATE_WARRANTY_DATE.ZCRM_UPDATE_WARRANTY_DATEResponse1> EnhancementCRM.HelperUnit.ZCRM_UPDATE_WARRANTY_DATE.ZWS_WARRANTY_DATE_V3.ZCRM_UPDATE_WARRANTY_DATEAsync(EnhancementCRM.HelperUnit.ZCRM_UPDATE_WARRANTY_DATE.ZCRM_UPDATE_WARRANTY_DATERequest request) {
            return base.Channel.ZCRM_UPDATE_WARRANTY_DATEAsync(request);
        }
        
        public System.Threading.Tasks.Task<EnhancementCRM.HelperUnit.ZCRM_UPDATE_WARRANTY_DATE.ZCRM_UPDATE_WARRANTY_DATEResponse1> ZCRM_UPDATE_WARRANTY_DATEAsync(EnhancementCRM.HelperUnit.ZCRM_UPDATE_WARRANTY_DATE.ZCRM_UPDATE_WARRANTY_DATE ZCRM_UPDATE_WARRANTY_DATE) {
            EnhancementCRM.HelperUnit.ZCRM_UPDATE_WARRANTY_DATE.ZCRM_UPDATE_WARRANTY_DATERequest inValue = new EnhancementCRM.HelperUnit.ZCRM_UPDATE_WARRANTY_DATE.ZCRM_UPDATE_WARRANTY_DATERequest();
            inValue.ZCRM_UPDATE_WARRANTY_DATE = ZCRM_UPDATE_WARRANTY_DATE;
            return ((EnhancementCRM.HelperUnit.ZCRM_UPDATE_WARRANTY_DATE.ZWS_WARRANTY_DATE_V3)(this)).ZCRM_UPDATE_WARRANTY_DATEAsync(inValue);
        }
    }
}
