//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrakNusSparepartSystem.Workflow.WebserviceSAP {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", ConfigurationName="WebserviceSAP.ZWEB_SERVICES_CRM")]
    public interface ZWEB_SERVICES_CRM {
        
        // CODEGEN: Generating message contract since the operation ZcrmStatusStock is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="urn:sap-com:document:sap:soap:functions:mc-style:ZWEB_SERVICES_CRM:ZcrmStatusStoc" +
            "kRequest", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TrakNusSparepartSystem.Workflow.WebserviceSAP.ZcrmStatusStockResponse1 ZcrmStatusStock(TrakNusSparepartSystem.Workflow.WebserviceSAP.ZcrmStatusStockRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:sap-com:document:sap:soap:functions:mc-style:ZWEB_SERVICES_CRM:ZcrmStatusStoc" +
            "kRequest", ReplyAction="*")]
        System.Threading.Tasks.Task<TrakNusSparepartSystem.Workflow.WebserviceSAP.ZcrmStatusStockResponse1> ZcrmStatusStockAsync(TrakNusSparepartSystem.Workflow.WebserviceSAP.ZcrmStatusStockRequest request);
        
        // CODEGEN: Generating message contract since the operation ZcrmCancelSo is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="urn:sap-com:document:sap:soap:functions:mc-style:ZWEB_SERVICES_CRM:ZcrmCancelSoRe" +
            "quest", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TrakNusSparepartSystem.Workflow.WebserviceSAP.ZcrmCancelSoResponse1 ZcrmCancelSo(TrakNusSparepartSystem.Workflow.WebserviceSAP.ZcrmCancelSoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:sap-com:document:sap:soap:functions:mc-style:ZWEB_SERVICES_CRM:ZcrmCancelSoRe" +
            "quest", ReplyAction="*")]
        System.Threading.Tasks.Task<TrakNusSparepartSystem.Workflow.WebserviceSAP.ZcrmCancelSoResponse1> ZcrmCancelSoAsync(TrakNusSparepartSystem.Workflow.WebserviceSAP.ZcrmCancelSoRequest request);
        
        // CODEGEN: Generating message contract since the operation ZcrmCreateSo is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="urn:sap-com:document:sap:soap:functions:mc-style:ZWEB_SERVICES_CRM:ZcrmCreateSoRe" +
            "quest", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TrakNusSparepartSystem.Workflow.WebserviceSAP.ZcrmCreateSoResponse1 ZcrmCreateSo(TrakNusSparepartSystem.Workflow.WebserviceSAP.ZcrmCreateSoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:sap-com:document:sap:soap:functions:mc-style:ZWEB_SERVICES_CRM:ZcrmCreateSoRe" +
            "quest", ReplyAction="*")]
        System.Threading.Tasks.Task<TrakNusSparepartSystem.Workflow.WebserviceSAP.ZcrmCreateSoResponse1> ZcrmCreateSoAsync(TrakNusSparepartSystem.Workflow.WebserviceSAP.ZcrmCreateSoRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZcrmStatusStock : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string csrfTokenField;
        
        private ZstrStatusCek[] statusCekField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string CsrfToken {
            get {
                return this.csrfTokenField;
            }
            set {
                this.csrfTokenField = value;
                this.RaisePropertyChanged("CsrfToken");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZstrStatusCek[] StatusCek {
            get {
                return this.statusCekField;
            }
            set {
                this.statusCekField = value;
                this.RaisePropertyChanged("StatusCek");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZstrStatusCek : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string partNumberField;
        
        private string branchField;
        
        private string uomField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string PartNumber {
            get {
                return this.partNumberField;
            }
            set {
                this.partNumberField = value;
                this.RaisePropertyChanged("PartNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Branch {
            get {
                return this.branchField;
            }
            set {
                this.branchField = value;
                this.RaisePropertyChanged("Branch");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Uom {
            get {
                return this.uomField;
            }
            set {
                this.uomField = value;
                this.RaisePropertyChanged("Uom");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZstrResultDo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string delnoField;
        
        private decimal delqtField;
        
        private string brnchField;
        
        private string matrlField;
        
        private string sonumField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Delno {
            get {
                return this.delnoField;
            }
            set {
                this.delnoField = value;
                this.RaisePropertyChanged("Delno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public decimal Delqt {
            get {
                return this.delqtField;
            }
            set {
                this.delqtField = value;
                this.RaisePropertyChanged("Delqt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Brnch {
            get {
                return this.brnchField;
            }
            set {
                this.brnchField = value;
                this.RaisePropertyChanged("Brnch");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string Matrl {
            get {
                return this.matrlField;
            }
            set {
                this.matrlField = value;
                this.RaisePropertyChanged("Matrl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string Sonum {
            get {
                return this.sonumField;
            }
            set {
                this.sonumField = value;
                this.RaisePropertyChanged("Sonum");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZstrDetailSo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string itmNumberField;
        
        private string materialField;
        
        private decimal targetQtyField;
        
        private string salesUnitField;
        
        private string itemCategField;
        
        private decimal condValueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string ItmNumber {
            get {
                return this.itmNumberField;
            }
            set {
                this.itmNumberField = value;
                this.RaisePropertyChanged("ItmNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Material {
            get {
                return this.materialField;
            }
            set {
                this.materialField = value;
                this.RaisePropertyChanged("Material");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public decimal TargetQty {
            get {
                return this.targetQtyField;
            }
            set {
                this.targetQtyField = value;
                this.RaisePropertyChanged("TargetQty");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string SalesUnit {
            get {
                return this.salesUnitField;
            }
            set {
                this.salesUnitField = value;
                this.RaisePropertyChanged("SalesUnit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string ItemCateg {
            get {
                return this.itemCategField;
            }
            set {
                this.itemCategField = value;
                this.RaisePropertyChanged("ItemCateg");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public decimal CondValue {
            get {
                return this.condValueField;
            }
            set {
                this.condValueField = value;
                this.RaisePropertyChanged("CondValue");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZstrStatusStock : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string partNumberField;
        
        private string branchField;
        
        private string uomField;
        
        private string stockField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string PartNumber {
            get {
                return this.partNumberField;
            }
            set {
                this.partNumberField = value;
                this.RaisePropertyChanged("PartNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Branch {
            get {
                return this.branchField;
            }
            set {
                this.branchField = value;
                this.RaisePropertyChanged("Branch");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Uom {
            get {
                return this.uomField;
            }
            set {
                this.uomField = value;
                this.RaisePropertyChanged("Uom");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string Stock {
            get {
                return this.stockField;
            }
            set {
                this.stockField = value;
                this.RaisePropertyChanged("Stock");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZcrmStatusStockResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string descriptionField;
        
        private string resultField;
        
        private ZstrStatusStock[] statusReturnField;
        
        private string syncDateField;
        
        private System.DateTime syncTimeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("Result");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZstrStatusStock[] StatusReturn {
            get {
                return this.statusReturnField;
            }
            set {
                this.statusReturnField = value;
                this.RaisePropertyChanged("StatusReturn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string SyncDate {
            get {
                return this.syncDateField;
            }
            set {
                this.syncDateField = value;
                this.RaisePropertyChanged("SyncDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="time", Order=4)]
        public System.DateTime SyncTime {
            get {
                return this.syncTimeField;
            }
            set {
                this.syncTimeField = value;
                this.RaisePropertyChanged("SyncTime");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZcrmStatusStockRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", Order=0)]
        public TrakNusSparepartSystem.Workflow.WebserviceSAP.ZcrmStatusStock ZcrmStatusStock;
        
        public ZcrmStatusStockRequest() {
        }
        
        public ZcrmStatusStockRequest(TrakNusSparepartSystem.Workflow.WebserviceSAP.ZcrmStatusStock ZcrmStatusStock) {
            this.ZcrmStatusStock = ZcrmStatusStock;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZcrmStatusStockResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", Order=0)]
        public TrakNusSparepartSystem.Workflow.WebserviceSAP.ZcrmStatusStockResponse ZcrmStatusStockResponse;
        
        public ZcrmStatusStockResponse1() {
        }
        
        public ZcrmStatusStockResponse1(TrakNusSparepartSystem.Workflow.WebserviceSAP.ZcrmStatusStockResponse ZcrmStatusStockResponse) {
            this.ZcrmStatusStockResponse = ZcrmStatusStockResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZcrmCancelSo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string csrfTokenField;
        
        private string salesdocumentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string CsrfToken {
            get {
                return this.csrfTokenField;
            }
            set {
                this.csrfTokenField = value;
                this.RaisePropertyChanged("CsrfToken");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Salesdocument {
            get {
                return this.salesdocumentField;
            }
            set {
                this.salesdocumentField = value;
                this.RaisePropertyChanged("Salesdocument");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZcrmCancelSoResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string descriptionField;
        
        private string resultField;
        
        private string syncDateField;
        
        private System.DateTime syncTimeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("Result");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string SyncDate {
            get {
                return this.syncDateField;
            }
            set {
                this.syncDateField = value;
                this.RaisePropertyChanged("SyncDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="time", Order=3)]
        public System.DateTime SyncTime {
            get {
                return this.syncTimeField;
            }
            set {
                this.syncTimeField = value;
                this.RaisePropertyChanged("SyncTime");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZcrmCancelSoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", Order=0)]
        public TrakNusSparepartSystem.Workflow.WebserviceSAP.ZcrmCancelSo ZcrmCancelSo;
        
        public ZcrmCancelSoRequest() {
        }
        
        public ZcrmCancelSoRequest(TrakNusSparepartSystem.Workflow.WebserviceSAP.ZcrmCancelSo ZcrmCancelSo) {
            this.ZcrmCancelSo = ZcrmCancelSo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZcrmCancelSoResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", Order=0)]
        public TrakNusSparepartSystem.Workflow.WebserviceSAP.ZcrmCancelSoResponse ZcrmCancelSoResponse;
        
        public ZcrmCancelSoResponse1() {
        }
        
        public ZcrmCancelSoResponse1(TrakNusSparepartSystem.Workflow.WebserviceSAP.ZcrmCancelSoResponse ZcrmCancelSoResponse) {
            this.ZcrmCancelSoResponse = ZcrmCancelSoResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZcrmCreateSo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string billToField;
        
        private string contactBillField;
        
        private string contactShipField;
        
        private string contactSlsField;
        
        private string contactSoldField;
        
        private string csrfTokenField;
        
        private string currencyField;
        
        private ZstrDetailSo[] detailSoField;
        
        private string distrChanField;
        
        private string divisionField;
        
        private string docTypeField;
        
        private string packNameField;
        
        private string packPriceField;
        
        private string packQtyField;
        
        private string packSlsunitField;
        
        private string packTypeField;
        
        private string partnNumbField;
        
        private string plantField;
        
        private string pmnttrmsField;
        
        private string priceGrpField;
        
        private string priceListField;
        
        private string purchDateField;
        
        private string purchNoCField;
        
        private string reqDateHField;
        
        private string salesOffField;
        
        private string salesOrgField;
        
        private string salesmanField;
        
        private string shipToField;
        
        private string soCrmNoField;
        
        private string soldToField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string BillTo {
            get {
                return this.billToField;
            }
            set {
                this.billToField = value;
                this.RaisePropertyChanged("BillTo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ContactBill {
            get {
                return this.contactBillField;
            }
            set {
                this.contactBillField = value;
                this.RaisePropertyChanged("ContactBill");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string ContactShip {
            get {
                return this.contactShipField;
            }
            set {
                this.contactShipField = value;
                this.RaisePropertyChanged("ContactShip");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string ContactSls {
            get {
                return this.contactSlsField;
            }
            set {
                this.contactSlsField = value;
                this.RaisePropertyChanged("ContactSls");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string ContactSold {
            get {
                return this.contactSoldField;
            }
            set {
                this.contactSoldField = value;
                this.RaisePropertyChanged("ContactSold");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string CsrfToken {
            get {
                return this.csrfTokenField;
            }
            set {
                this.csrfTokenField = value;
                this.RaisePropertyChanged("CsrfToken");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string Currency {
            get {
                return this.currencyField;
            }
            set {
                this.currencyField = value;
                this.RaisePropertyChanged("Currency");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZstrDetailSo[] DetailSo {
            get {
                return this.detailSoField;
            }
            set {
                this.detailSoField = value;
                this.RaisePropertyChanged("DetailSo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string DistrChan {
            get {
                return this.distrChanField;
            }
            set {
                this.distrChanField = value;
                this.RaisePropertyChanged("DistrChan");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string Division {
            get {
                return this.divisionField;
            }
            set {
                this.divisionField = value;
                this.RaisePropertyChanged("Division");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string DocType {
            get {
                return this.docTypeField;
            }
            set {
                this.docTypeField = value;
                this.RaisePropertyChanged("DocType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string PackName {
            get {
                return this.packNameField;
            }
            set {
                this.packNameField = value;
                this.RaisePropertyChanged("PackName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string PackPrice {
            get {
                return this.packPriceField;
            }
            set {
                this.packPriceField = value;
                this.RaisePropertyChanged("PackPrice");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string PackQty {
            get {
                return this.packQtyField;
            }
            set {
                this.packQtyField = value;
                this.RaisePropertyChanged("PackQty");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string PackSlsunit {
            get {
                return this.packSlsunitField;
            }
            set {
                this.packSlsunitField = value;
                this.RaisePropertyChanged("PackSlsunit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string PackType {
            get {
                return this.packTypeField;
            }
            set {
                this.packTypeField = value;
                this.RaisePropertyChanged("PackType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public string PartnNumb {
            get {
                return this.partnNumbField;
            }
            set {
                this.partnNumbField = value;
                this.RaisePropertyChanged("PartnNumb");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public string Plant {
            get {
                return this.plantField;
            }
            set {
                this.plantField = value;
                this.RaisePropertyChanged("Plant");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public string Pmnttrms {
            get {
                return this.pmnttrmsField;
            }
            set {
                this.pmnttrmsField = value;
                this.RaisePropertyChanged("Pmnttrms");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
        public string PriceGrp {
            get {
                return this.priceGrpField;
            }
            set {
                this.priceGrpField = value;
                this.RaisePropertyChanged("PriceGrp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=20)]
        public string PriceList {
            get {
                return this.priceListField;
            }
            set {
                this.priceListField = value;
                this.RaisePropertyChanged("PriceList");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=21)]
        public string PurchDate {
            get {
                return this.purchDateField;
            }
            set {
                this.purchDateField = value;
                this.RaisePropertyChanged("PurchDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=22)]
        public string PurchNoC {
            get {
                return this.purchNoCField;
            }
            set {
                this.purchNoCField = value;
                this.RaisePropertyChanged("PurchNoC");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=23)]
        public string ReqDateH {
            get {
                return this.reqDateHField;
            }
            set {
                this.reqDateHField = value;
                this.RaisePropertyChanged("ReqDateH");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=24)]
        public string SalesOff {
            get {
                return this.salesOffField;
            }
            set {
                this.salesOffField = value;
                this.RaisePropertyChanged("SalesOff");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=25)]
        public string SalesOrg {
            get {
                return this.salesOrgField;
            }
            set {
                this.salesOrgField = value;
                this.RaisePropertyChanged("SalesOrg");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=26)]
        public string Salesman {
            get {
                return this.salesmanField;
            }
            set {
                this.salesmanField = value;
                this.RaisePropertyChanged("Salesman");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=27)]
        public string ShipTo {
            get {
                return this.shipToField;
            }
            set {
                this.shipToField = value;
                this.RaisePropertyChanged("ShipTo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=28)]
        public string SoCrmNo {
            get {
                return this.soCrmNoField;
            }
            set {
                this.soCrmNoField = value;
                this.RaisePropertyChanged("SoCrmNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=29)]
        public string SoldTo {
            get {
                return this.soldToField;
            }
            set {
                this.soldToField = value;
                this.RaisePropertyChanged("SoldTo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZcrmCreateSoResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string descriptionField;
        
        private string resultField;
        
        private ZstrResultDo[] resultDoField;
        
        private string syncDateField;
        
        private System.DateTime syncTimeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("Result");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZstrResultDo[] ResultDo {
            get {
                return this.resultDoField;
            }
            set {
                this.resultDoField = value;
                this.RaisePropertyChanged("ResultDo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string SyncDate {
            get {
                return this.syncDateField;
            }
            set {
                this.syncDateField = value;
                this.RaisePropertyChanged("SyncDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="time", Order=4)]
        public System.DateTime SyncTime {
            get {
                return this.syncTimeField;
            }
            set {
                this.syncTimeField = value;
                this.RaisePropertyChanged("SyncTime");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZcrmCreateSoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", Order=0)]
        public TrakNusSparepartSystem.Workflow.WebserviceSAP.ZcrmCreateSo ZcrmCreateSo;
        
        public ZcrmCreateSoRequest() {
        }
        
        public ZcrmCreateSoRequest(TrakNusSparepartSystem.Workflow.WebserviceSAP.ZcrmCreateSo ZcrmCreateSo) {
            this.ZcrmCreateSo = ZcrmCreateSo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZcrmCreateSoResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", Order=0)]
        public TrakNusSparepartSystem.Workflow.WebserviceSAP.ZcrmCreateSoResponse ZcrmCreateSoResponse;
        
        public ZcrmCreateSoResponse1() {
        }
        
        public ZcrmCreateSoResponse1(TrakNusSparepartSystem.Workflow.WebserviceSAP.ZcrmCreateSoResponse ZcrmCreateSoResponse) {
            this.ZcrmCreateSoResponse = ZcrmCreateSoResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ZWEB_SERVICES_CRMChannel : TrakNusSparepartSystem.Workflow.WebserviceSAP.ZWEB_SERVICES_CRM, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ZWEB_SERVICES_CRMClient : System.ServiceModel.ClientBase<TrakNusSparepartSystem.Workflow.WebserviceSAP.ZWEB_SERVICES_CRM>, TrakNusSparepartSystem.Workflow.WebserviceSAP.ZWEB_SERVICES_CRM {
        
        public ZWEB_SERVICES_CRMClient() {
        }
        
        public ZWEB_SERVICES_CRMClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ZWEB_SERVICES_CRMClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ZWEB_SERVICES_CRMClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ZWEB_SERVICES_CRMClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TrakNusSparepartSystem.Workflow.WebserviceSAP.ZcrmStatusStockResponse1 TrakNusSparepartSystem.Workflow.WebserviceSAP.ZWEB_SERVICES_CRM.ZcrmStatusStock(TrakNusSparepartSystem.Workflow.WebserviceSAP.ZcrmStatusStockRequest request) {
            return base.Channel.ZcrmStatusStock(request);
        }
        
        public TrakNusSparepartSystem.Workflow.WebserviceSAP.ZcrmStatusStockResponse ZcrmStatusStock(TrakNusSparepartSystem.Workflow.WebserviceSAP.ZcrmStatusStock ZcrmStatusStock1) {
            TrakNusSparepartSystem.Workflow.WebserviceSAP.ZcrmStatusStockRequest inValue = new TrakNusSparepartSystem.Workflow.WebserviceSAP.ZcrmStatusStockRequest();
            inValue.ZcrmStatusStock = ZcrmStatusStock1;
            TrakNusSparepartSystem.Workflow.WebserviceSAP.ZcrmStatusStockResponse1 retVal = ((TrakNusSparepartSystem.Workflow.WebserviceSAP.ZWEB_SERVICES_CRM)(this)).ZcrmStatusStock(inValue);
            return retVal.ZcrmStatusStockResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TrakNusSparepartSystem.Workflow.WebserviceSAP.ZcrmStatusStockResponse1> TrakNusSparepartSystem.Workflow.WebserviceSAP.ZWEB_SERVICES_CRM.ZcrmStatusStockAsync(TrakNusSparepartSystem.Workflow.WebserviceSAP.ZcrmStatusStockRequest request) {
            return base.Channel.ZcrmStatusStockAsync(request);
        }
        
        public System.Threading.Tasks.Task<TrakNusSparepartSystem.Workflow.WebserviceSAP.ZcrmStatusStockResponse1> ZcrmStatusStockAsync(TrakNusSparepartSystem.Workflow.WebserviceSAP.ZcrmStatusStock ZcrmStatusStock) {
            TrakNusSparepartSystem.Workflow.WebserviceSAP.ZcrmStatusStockRequest inValue = new TrakNusSparepartSystem.Workflow.WebserviceSAP.ZcrmStatusStockRequest();
            inValue.ZcrmStatusStock = ZcrmStatusStock;
            return ((TrakNusSparepartSystem.Workflow.WebserviceSAP.ZWEB_SERVICES_CRM)(this)).ZcrmStatusStockAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TrakNusSparepartSystem.Workflow.WebserviceSAP.ZcrmCancelSoResponse1 TrakNusSparepartSystem.Workflow.WebserviceSAP.ZWEB_SERVICES_CRM.ZcrmCancelSo(TrakNusSparepartSystem.Workflow.WebserviceSAP.ZcrmCancelSoRequest request) {
            return base.Channel.ZcrmCancelSo(request);
        }
        
        public TrakNusSparepartSystem.Workflow.WebserviceSAP.ZcrmCancelSoResponse ZcrmCancelSo(TrakNusSparepartSystem.Workflow.WebserviceSAP.ZcrmCancelSo ZcrmCancelSo1) {
            TrakNusSparepartSystem.Workflow.WebserviceSAP.ZcrmCancelSoRequest inValue = new TrakNusSparepartSystem.Workflow.WebserviceSAP.ZcrmCancelSoRequest();
            inValue.ZcrmCancelSo = ZcrmCancelSo1;
            TrakNusSparepartSystem.Workflow.WebserviceSAP.ZcrmCancelSoResponse1 retVal = ((TrakNusSparepartSystem.Workflow.WebserviceSAP.ZWEB_SERVICES_CRM)(this)).ZcrmCancelSo(inValue);
            return retVal.ZcrmCancelSoResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TrakNusSparepartSystem.Workflow.WebserviceSAP.ZcrmCancelSoResponse1> TrakNusSparepartSystem.Workflow.WebserviceSAP.ZWEB_SERVICES_CRM.ZcrmCancelSoAsync(TrakNusSparepartSystem.Workflow.WebserviceSAP.ZcrmCancelSoRequest request) {
            return base.Channel.ZcrmCancelSoAsync(request);
        }
        
        public System.Threading.Tasks.Task<TrakNusSparepartSystem.Workflow.WebserviceSAP.ZcrmCancelSoResponse1> ZcrmCancelSoAsync(TrakNusSparepartSystem.Workflow.WebserviceSAP.ZcrmCancelSo ZcrmCancelSo) {
            TrakNusSparepartSystem.Workflow.WebserviceSAP.ZcrmCancelSoRequest inValue = new TrakNusSparepartSystem.Workflow.WebserviceSAP.ZcrmCancelSoRequest();
            inValue.ZcrmCancelSo = ZcrmCancelSo;
            return ((TrakNusSparepartSystem.Workflow.WebserviceSAP.ZWEB_SERVICES_CRM)(this)).ZcrmCancelSoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TrakNusSparepartSystem.Workflow.WebserviceSAP.ZcrmCreateSoResponse1 TrakNusSparepartSystem.Workflow.WebserviceSAP.ZWEB_SERVICES_CRM.ZcrmCreateSo(TrakNusSparepartSystem.Workflow.WebserviceSAP.ZcrmCreateSoRequest request) {
            return base.Channel.ZcrmCreateSo(request);
        }
        
        public TrakNusSparepartSystem.Workflow.WebserviceSAP.ZcrmCreateSoResponse ZcrmCreateSo(TrakNusSparepartSystem.Workflow.WebserviceSAP.ZcrmCreateSo ZcrmCreateSo1) {
            TrakNusSparepartSystem.Workflow.WebserviceSAP.ZcrmCreateSoRequest inValue = new TrakNusSparepartSystem.Workflow.WebserviceSAP.ZcrmCreateSoRequest();
            inValue.ZcrmCreateSo = ZcrmCreateSo1;
            TrakNusSparepartSystem.Workflow.WebserviceSAP.ZcrmCreateSoResponse1 retVal = ((TrakNusSparepartSystem.Workflow.WebserviceSAP.ZWEB_SERVICES_CRM)(this)).ZcrmCreateSo(inValue);
            return retVal.ZcrmCreateSoResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TrakNusSparepartSystem.Workflow.WebserviceSAP.ZcrmCreateSoResponse1> TrakNusSparepartSystem.Workflow.WebserviceSAP.ZWEB_SERVICES_CRM.ZcrmCreateSoAsync(TrakNusSparepartSystem.Workflow.WebserviceSAP.ZcrmCreateSoRequest request) {
            return base.Channel.ZcrmCreateSoAsync(request);
        }
        
        public System.Threading.Tasks.Task<TrakNusSparepartSystem.Workflow.WebserviceSAP.ZcrmCreateSoResponse1> ZcrmCreateSoAsync(TrakNusSparepartSystem.Workflow.WebserviceSAP.ZcrmCreateSo ZcrmCreateSo) {
            TrakNusSparepartSystem.Workflow.WebserviceSAP.ZcrmCreateSoRequest inValue = new TrakNusSparepartSystem.Workflow.WebserviceSAP.ZcrmCreateSoRequest();
            inValue.ZcrmCreateSo = ZcrmCreateSo;
            return ((TrakNusSparepartSystem.Workflow.WebserviceSAP.ZWEB_SERVICES_CRM)(this)).ZcrmCreateSoAsync(inValue);
        }
    }
}
