//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// Created via this command line: "C:\Users\USER\AppData\Roaming\MscrmTools\XrmToolBox\Plugins\DLaB.EarlyBoundGenerator\crmsvcutil.exe" /url:"http://10.0.10.43/TraktorNusantara" /generateActions /out:"C:\Users\USER\AppData\Roaming\MscrmTools\XrmToolBox\Settings\EBG\Actions.cs" /namespace:"CrmEarlyBound" /codecustomization:"DLaB.CrmSvcUtilExtensions.Action.CustomizeCodeDomService,DLaB.CrmSvcUtilExtensions" /codegenerationservice:"DLaB.CrmSvcUtilExtensions.Action.CustomCodeGenerationService,DLaB.CrmSvcUtilExtensions" /codewriterfilter:"DLaB.CrmSvcUtilExtensions.Action.CodeWriterFilterService,DLaB.CrmSvcUtilExtensions" /metadataproviderservice:"DLaB.CrmSvcUtilExtensions.BaseMetadataProviderService,DLaB.CrmSvcUtilExtensions" /username:"dev.crm" /password:"**************" /domain:"Traknus" 
//------------------------------------------------------------------------------

namespace CrmEarlyBound
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/ibizcs/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("ibizcs_IBIZActionuntukExtendPlafond")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9479")]
	public partial class ibizcs_IBIZActionuntukExtendPlafondRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public Microsoft.Xrm.Sdk.EntityReference Target
		{
			get
			{
				if (this.Parameters.Contains("Target"))
				{
					return ((Microsoft.Xrm.Sdk.EntityReference)(this.Parameters["Target"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityReference);
				}
			}
			set
			{
				this.Parameters["Target"] = value;
			}
		}
		
		public ibizcs_IBIZActionuntukExtendPlafondRequest()
		{
			this.RequestName = "ibizcs_IBIZActionuntukExtendPlafond";
			this.Target = default(Microsoft.Xrm.Sdk.EntityReference);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/ibizcs/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("ibizcs_IBIZActionuntukExtendPlafond")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9479")]
	public partial class ibizcs_IBIZActionuntukExtendPlafondResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public ibizcs_IBIZActionuntukExtendPlafondResponse()
		{
		}
		
		public string Message
		{
			get
			{
				if (this.Results.Contains("Message"))
				{
					return ((string)(this.Results["Message"]));
				}
				else
				{
					return default(string);
				}
			}
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/ibizcs/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("ibizcs_ActionErrorMessage")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9479")]
	public partial class ibizcs_ActionErrorMessageRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public string BusinessUnit
		{
			get
			{
				if (this.Parameters.Contains("BusinessUnit"))
				{
					return ((string)(this.Parameters["BusinessUnit"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["BusinessUnit"] = value;
			}
		}
		
		public string CustomerName
		{
			get
			{
				if (this.Parameters.Contains("CustomerName"))
				{
					return ((string)(this.Parameters["CustomerName"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["CustomerName"] = value;
			}
		}
		
		public int TotalOD
		{
			get
			{
				if (this.Parameters.Contains("TotalOD"))
				{
					return ((int)(this.Parameters["TotalOD"]));
				}
				else
				{
					return default(int);
				}
			}
			set
			{
				this.Parameters["TotalOD"] = value;
			}
		}
		
		public Microsoft.Xrm.Sdk.EntityReference Target
		{
			get
			{
				if (this.Parameters.Contains("Target"))
				{
					return ((Microsoft.Xrm.Sdk.EntityReference)(this.Parameters["Target"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityReference);
				}
			}
			set
			{
				this.Parameters["Target"] = value;
			}
		}
		
		public ibizcs_ActionErrorMessageRequest()
		{
			this.RequestName = "ibizcs_ActionErrorMessage";
			this.BusinessUnit = default(string);
			this.CustomerName = default(string);
			this.TotalOD = default(int);
			this.Target = default(Microsoft.Xrm.Sdk.EntityReference);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/ibizcs/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("ibizcs_ActionErrorMessage")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9479")]
	public partial class ibizcs_ActionErrorMessageResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public ibizcs_ActionErrorMessageResponse()
		{
		}
		
		public string MessageOutput
		{
			get
			{
				if (this.Results.Contains("MessageOutput"))
				{
					return ((string)(this.Results["MessageOutput"]));
				}
				else
				{
					return default(string);
				}
			}
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("new_Sendemailwhenpopulationexpired")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9479")]
	public partial class new_SendemailwhenpopulationexpiredRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public Microsoft.Xrm.Sdk.EntityReference Target
		{
			get
			{
				if (this.Parameters.Contains("Target"))
				{
					return ((Microsoft.Xrm.Sdk.EntityReference)(this.Parameters["Target"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityReference);
				}
			}
			set
			{
				this.Parameters["Target"] = value;
			}
		}
		
		public new_SendemailwhenpopulationexpiredRequest()
		{
			this.RequestName = "new_Sendemailwhenpopulationexpired";
			this.Target = default(Microsoft.Xrm.Sdk.EntityReference);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("new_Sendemailwhenpopulationexpired")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9479")]
	public partial class new_SendemailwhenpopulationexpiredResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public new_SendemailwhenpopulationexpiredResponse()
		{
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/ibizcs/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("ibizcs_IBIZCheckCLWO")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9479")]
	public partial class ibizcs_IBIZCheckCLWORequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public Microsoft.Xrm.Sdk.EntityReference Target
		{
			get
			{
				if (this.Parameters.Contains("Target"))
				{
					return ((Microsoft.Xrm.Sdk.EntityReference)(this.Parameters["Target"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityReference);
				}
			}
			set
			{
				this.Parameters["Target"] = value;
			}
		}
		
		public ibizcs_IBIZCheckCLWORequest()
		{
			this.RequestName = "ibizcs_IBIZCheckCLWO";
			this.Target = default(Microsoft.Xrm.Sdk.EntityReference);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/ibizcs/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("ibizcs_IBIZCheckCLWO")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9479")]
	public partial class ibizcs_IBIZCheckCLWOResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public ibizcs_IBIZCheckCLWOResponse()
		{
		}
		
		public string ErrorMessage
		{
			get
			{
				if (this.Results.Contains("ErrorMessage"))
				{
					return ((string)(this.Results["ErrorMessage"]));
				}
				else
				{
					return default(string);
				}
			}
		}
		
		public bool StatusCL
		{
			get
			{
				if (this.Results.Contains("StatusCL"))
				{
					return ((bool)(this.Results["StatusCL"]));
				}
				else
				{
					return default(bool);
				}
			}
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/ibizcs/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("ibizcs_IBIZCSCheckCLWO1")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9479")]
	public partial class ibizcs_IBIZCSCheckCLWO1Request : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public Microsoft.Xrm.Sdk.EntityReference Target
		{
			get
			{
				if (this.Parameters.Contains("Target"))
				{
					return ((Microsoft.Xrm.Sdk.EntityReference)(this.Parameters["Target"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityReference);
				}
			}
			set
			{
				this.Parameters["Target"] = value;
			}
		}
		
		public ibizcs_IBIZCSCheckCLWO1Request()
		{
			this.RequestName = "ibizcs_IBIZCSCheckCLWO1";
			this.Target = default(Microsoft.Xrm.Sdk.EntityReference);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/ibizcs/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("ibizcs_IBIZCSCheckCLWO1")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9479")]
	public partial class ibizcs_IBIZCSCheckCLWO1Response : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public ibizcs_IBIZCSCheckCLWO1Response()
		{
		}
		
		public string ErrorMessage
		{
			get
			{
				if (this.Results.Contains("ErrorMessage"))
				{
					return ((string)(this.Results["ErrorMessage"]));
				}
				else
				{
					return default(string);
				}
			}
		}
		
		public bool StatusCL
		{
			get
			{
				if (this.Results.Contains("StatusCL"))
				{
					return ((bool)(this.Results["StatusCL"]));
				}
				else
				{
					return default(bool);
				}
			}
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/ibizcs/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("ibizcs_IBIZCSCheckCLWOCheckQualityandPlafond")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9479")]
	public partial class ibizcs_IBIZCSCheckCLWOCheckQualityandPlafondRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public Microsoft.Xrm.Sdk.EntityReference Target
		{
			get
			{
				if (this.Parameters.Contains("Target"))
				{
					return ((Microsoft.Xrm.Sdk.EntityReference)(this.Parameters["Target"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityReference);
				}
			}
			set
			{
				this.Parameters["Target"] = value;
			}
		}
		
		public ibizcs_IBIZCSCheckCLWOCheckQualityandPlafondRequest()
		{
			this.RequestName = "ibizcs_IBIZCSCheckCLWOCheckQualityandPlafond";
			this.Target = default(Microsoft.Xrm.Sdk.EntityReference);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/ibizcs/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("ibizcs_IBIZCSCheckCLWOCheckQualityandPlafond")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9479")]
	public partial class ibizcs_IBIZCSCheckCLWOCheckQualityandPlafondResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public ibizcs_IBIZCSCheckCLWOCheckQualityandPlafondResponse()
		{
		}
		
		public string ErrorMessage
		{
			get
			{
				if (this.Results.Contains("ErrorMessage"))
				{
					return ((string)(this.Results["ErrorMessage"]));
				}
				else
				{
					return default(string);
				}
			}
		}
		
		public bool StatusCL
		{
			get
			{
				if (this.Results.Contains("StatusCL"))
				{
					return ((bool)(this.Results["StatusCL"]));
				}
				else
				{
					return default(bool);
				}
			}
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/ibizcs/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("ibizcs_IBIZCSCheckCLSO")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9479")]
	public partial class ibizcs_IBIZCSCheckCLSORequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public Microsoft.Xrm.Sdk.EntityReference Target
		{
			get
			{
				if (this.Parameters.Contains("Target"))
				{
					return ((Microsoft.Xrm.Sdk.EntityReference)(this.Parameters["Target"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityReference);
				}
			}
			set
			{
				this.Parameters["Target"] = value;
			}
		}
		
		public ibizcs_IBIZCSCheckCLSORequest()
		{
			this.RequestName = "ibizcs_IBIZCSCheckCLSO";
			this.Target = default(Microsoft.Xrm.Sdk.EntityReference);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/ibizcs/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("ibizcs_IBIZCSCheckCLSO")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9479")]
	public partial class ibizcs_IBIZCSCheckCLSOResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public ibizcs_IBIZCSCheckCLSOResponse()
		{
		}
		
		public string ErrorMessage
		{
			get
			{
				if (this.Results.Contains("ErrorMessage"))
				{
					return ((string)(this.Results["ErrorMessage"]));
				}
				else
				{
					return default(string);
				}
			}
		}
		
		public bool StatusCL
		{
			get
			{
				if (this.Results.Contains("StatusCL"))
				{
					return ((bool)(this.Results["StatusCL"]));
				}
				else
				{
					return default(bool);
				}
			}
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/ibizcs/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("ibizcs_IBIZCSCheckCLSOCheckQualityandPlafond")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9479")]
	public partial class ibizcs_IBIZCSCheckCLSOCheckQualityandPlafondRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public Microsoft.Xrm.Sdk.EntityReference Target
		{
			get
			{
				if (this.Parameters.Contains("Target"))
				{
					return ((Microsoft.Xrm.Sdk.EntityReference)(this.Parameters["Target"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityReference);
				}
			}
			set
			{
				this.Parameters["Target"] = value;
			}
		}
		
		public ibizcs_IBIZCSCheckCLSOCheckQualityandPlafondRequest()
		{
			this.RequestName = "ibizcs_IBIZCSCheckCLSOCheckQualityandPlafond";
			this.Target = default(Microsoft.Xrm.Sdk.EntityReference);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/ibizcs/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("ibizcs_IBIZCSCheckCLSOCheckQualityandPlafond")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9479")]
	public partial class ibizcs_IBIZCSCheckCLSOCheckQualityandPlafondResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public ibizcs_IBIZCSCheckCLSOCheckQualityandPlafondResponse()
		{
		}
		
		public string ErrorMessage
		{
			get
			{
				if (this.Results.Contains("ErrorMessage"))
				{
					return ((string)(this.Results["ErrorMessage"]));
				}
				else
				{
					return default(string);
				}
			}
		}
		
		public bool StatusCL
		{
			get
			{
				if (this.Results.Contains("StatusCL"))
				{
					return ((bool)(this.Results["StatusCL"]));
				}
				else
				{
					return default(bool);
				}
			}
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/ibizcs/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("ibizcs_GetRunningNumberAction")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9479")]
	public partial class ibizcs_GetRunningNumberActionRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public string RunningNumberName
		{
			get
			{
				if (this.Parameters.Contains("RunningNumberName"))
				{
					return ((string)(this.Parameters["RunningNumberName"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["RunningNumberName"] = value;
			}
		}
		
		public Microsoft.Xrm.Sdk.EntityReference Target
		{
			get
			{
				if (this.Parameters.Contains("Target"))
				{
					return ((Microsoft.Xrm.Sdk.EntityReference)(this.Parameters["Target"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityReference);
				}
			}
			set
			{
				this.Parameters["Target"] = value;
			}
		}
		
		public ibizcs_GetRunningNumberActionRequest()
		{
			this.RequestName = "ibizcs_GetRunningNumberAction";
			this.RunningNumberName = default(string);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/ibizcs/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("ibizcs_GetRunningNumberAction")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9479")]
	public partial class ibizcs_GetRunningNumberActionResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public ibizcs_GetRunningNumberActionResponse()
		{
		}
		
		public int RunningNumberOutput
		{
			get
			{
				if (this.Results.Contains("RunningNumberOutput"))
				{
					return ((int)(this.Results["RunningNumberOutput"]));
				}
				else
				{
					return default(int);
				}
			}
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/ibizcs/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("ibizcs_IBIZRecalculateOperatingPartyAction")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9479")]
	public partial class ibizcs_IBIZRecalculateOperatingPartyActionRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public Microsoft.Xrm.Sdk.EntityReference Target
		{
			get
			{
				if (this.Parameters.Contains("Target"))
				{
					return ((Microsoft.Xrm.Sdk.EntityReference)(this.Parameters["Target"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityReference);
				}
			}
			set
			{
				this.Parameters["Target"] = value;
			}
		}
		
		public ibizcs_IBIZRecalculateOperatingPartyActionRequest()
		{
			this.RequestName = "ibizcs_IBIZRecalculateOperatingPartyAction";
			this.Target = default(Microsoft.Xrm.Sdk.EntityReference);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/ibizcs/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("ibizcs_IBIZRecalculateOperatingPartyAction")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9479")]
	public partial class ibizcs_IBIZRecalculateOperatingPartyActionResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public ibizcs_IBIZRecalculateOperatingPartyActionResponse()
		{
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("new_Tes")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9479")]
	public partial class new_TesRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public Microsoft.Xrm.Sdk.EntityReference Target
		{
			get
			{
				if (this.Parameters.Contains("Target"))
				{
					return ((Microsoft.Xrm.Sdk.EntityReference)(this.Parameters["Target"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityReference);
				}
			}
			set
			{
				this.Parameters["Target"] = value;
			}
		}
		
		public new_TesRequest()
		{
			this.RequestName = "new_Tes";
			this.Target = default(Microsoft.Xrm.Sdk.EntityReference);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("new_Tes")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9479")]
	public partial class new_TesResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public new_TesResponse()
		{
		}
		
		public bool Bool
		{
			get
			{
				if (this.Results.Contains("Bool"))
				{
					return ((bool)(this.Results["Bool"]));
				}
				else
				{
					return default(bool);
				}
			}
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/tss/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("tss_AGITMarketSizeActionGenerateMasterMarketSize")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9479")]
	public partial class tss_AGITMarketSizeActionGenerateMasterMarketSizeRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public Microsoft.Xrm.Sdk.EntityReference Target
		{
			get
			{
				if (this.Parameters.Contains("Target"))
				{
					return ((Microsoft.Xrm.Sdk.EntityReference)(this.Parameters["Target"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityReference);
				}
			}
			set
			{
				this.Parameters["Target"] = value;
			}
		}
		
		public tss_AGITMarketSizeActionGenerateMasterMarketSizeRequest()
		{
			this.RequestName = "tss_AGITMarketSizeActionGenerateMasterMarketSize";
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/tss/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("tss_AGITMarketSizeActionGenerateMasterMarketSize")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9479")]
	public partial class tss_AGITMarketSizeActionGenerateMasterMarketSizeResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public tss_AGITMarketSizeActionGenerateMasterMarketSizeResponse()
		{
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/tss/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("tss_AGITProspectPartActionGenerateProspectPartHeader")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9479")]
	public partial class tss_AGITProspectPartActionGenerateProspectPartHeaderRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public Microsoft.Xrm.Sdk.EntityReference Target
		{
			get
			{
				if (this.Parameters.Contains("Target"))
				{
					return ((Microsoft.Xrm.Sdk.EntityReference)(this.Parameters["Target"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityReference);
				}
			}
			set
			{
				this.Parameters["Target"] = value;
			}
		}
		
		public tss_AGITProspectPartActionGenerateProspectPartHeaderRequest()
		{
			this.RequestName = "tss_AGITProspectPartActionGenerateProspectPartHeader";
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/tss/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("tss_AGITProspectPartActionGenerateProspectPartHeader")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9479")]
	public partial class tss_AGITProspectPartActionGenerateProspectPartHeaderResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public tss_AGITProspectPartActionGenerateProspectPartHeaderResponse()
		{
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/ibizcs/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("ibizcs_IBIZCSCheckCLWOCheckQuality")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9479")]
	public partial class ibizcs_IBIZCSCheckCLWOCheckQualityRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public Microsoft.Xrm.Sdk.EntityReference Target
		{
			get
			{
				if (this.Parameters.Contains("Target"))
				{
					return ((Microsoft.Xrm.Sdk.EntityReference)(this.Parameters["Target"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityReference);
				}
			}
			set
			{
				this.Parameters["Target"] = value;
			}
		}
		
		public ibizcs_IBIZCSCheckCLWOCheckQualityRequest()
		{
			this.RequestName = "ibizcs_IBIZCSCheckCLWOCheckQuality";
			this.Target = default(Microsoft.Xrm.Sdk.EntityReference);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/ibizcs/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("ibizcs_IBIZCSCheckCLWOCheckQuality")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9479")]
	public partial class ibizcs_IBIZCSCheckCLWOCheckQualityResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public ibizcs_IBIZCSCheckCLWOCheckQualityResponse()
		{
		}
		
		public string ErrorMessage
		{
			get
			{
				if (this.Results.Contains("ErrorMessage"))
				{
					return ((string)(this.Results["ErrorMessage"]));
				}
				else
				{
					return default(string);
				}
			}
		}
		
		public bool StatusCL
		{
			get
			{
				if (this.Results.Contains("StatusCL"))
				{
					return ((bool)(this.Results["StatusCL"]));
				}
				else
				{
					return default(bool);
				}
			}
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/tss/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("tss_AGITMarketSizeResultPssActionConfirmMarketSizeResultPSS")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9479")]
	public partial class tss_AGITMarketSizeResultPssActionConfirmMarketSizeResultPSSRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public string RecordID
		{
			get
			{
				if (this.Parameters.Contains("RecordID"))
				{
					return ((string)(this.Parameters["RecordID"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["RecordID"] = value;
			}
		}
		
		public Microsoft.Xrm.Sdk.EntityReference Target
		{
			get
			{
				if (this.Parameters.Contains("Target"))
				{
					return ((Microsoft.Xrm.Sdk.EntityReference)(this.Parameters["Target"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityReference);
				}
			}
			set
			{
				this.Parameters["Target"] = value;
			}
		}
		
		public tss_AGITMarketSizeResultPssActionConfirmMarketSizeResultPSSRequest()
		{
			this.RequestName = "tss_AGITMarketSizeResultPssActionConfirmMarketSizeResultPSS";
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/tss/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("tss_AGITMarketSizeResultPssActionConfirmMarketSizeResultPSS")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9479")]
	public partial class tss_AGITMarketSizeResultPssActionConfirmMarketSizeResultPSSResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public tss_AGITMarketSizeResultPssActionConfirmMarketSizeResultPSSResponse()
		{
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/ibizcs/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("ibizcs_IBIZCSCheckCLWOCheckCLQuality")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9479")]
	public partial class ibizcs_IBIZCSCheckCLWOCheckCLQualityRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public Microsoft.Xrm.Sdk.EntityReference Target
		{
			get
			{
				if (this.Parameters.Contains("Target"))
				{
					return ((Microsoft.Xrm.Sdk.EntityReference)(this.Parameters["Target"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityReference);
				}
			}
			set
			{
				this.Parameters["Target"] = value;
			}
		}
		
		public ibizcs_IBIZCSCheckCLWOCheckCLQualityRequest()
		{
			this.RequestName = "ibizcs_IBIZCSCheckCLWOCheckCLQuality";
			this.Target = default(Microsoft.Xrm.Sdk.EntityReference);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/ibizcs/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("ibizcs_IBIZCSCheckCLWOCheckCLQuality")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9479")]
	public partial class ibizcs_IBIZCSCheckCLWOCheckCLQualityResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public ibizcs_IBIZCSCheckCLWOCheckCLQualityResponse()
		{
		}
		
		public string ErrorMessage
		{
			get
			{
				if (this.Results.Contains("ErrorMessage"))
				{
					return ((string)(this.Results["ErrorMessage"]));
				}
				else
				{
					return default(string);
				}
			}
		}
		
		public bool StatusCL
		{
			get
			{
				if (this.Results.Contains("StatusCL"))
				{
					return ((bool)(this.Results["StatusCL"]));
				}
				else
				{
					return default(bool);
				}
			}
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/tss/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("tss_AGITProspectPartActionGenerateProspectPartFromPotentialProspectSubLine")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9479")]
	public partial class tss_AGITProspectPartActionGenerateProspectPartFromPotentialProspectSubLineRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public string RecordID
		{
			get
			{
				if (this.Parameters.Contains("RecordID"))
				{
					return ((string)(this.Parameters["RecordID"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["RecordID"] = value;
			}
		}
		
		public Microsoft.Xrm.Sdk.EntityReference Target
		{
			get
			{
				if (this.Parameters.Contains("Target"))
				{
					return ((Microsoft.Xrm.Sdk.EntityReference)(this.Parameters["Target"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityReference);
				}
			}
			set
			{
				this.Parameters["Target"] = value;
			}
		}
		
		public tss_AGITProspectPartActionGenerateProspectPartFromPotentialProspectSubLineRequest()
		{
			this.RequestName = "tss_AGITProspectPartActionGenerateProspectPartFromPotentialProspectSubLine";
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/tss/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("tss_AGITProspectPartActionGenerateProspectPartFromPotentialProspectSubLine")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9479")]
	public partial class tss_AGITProspectPartActionGenerateProspectPartFromPotentialProspectSubLineResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public tss_AGITProspectPartActionGenerateProspectPartFromPotentialProspectSubLineResponse()
		{
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("new_ReviseKeyAccountAction")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9479")]
	public partial class new_ReviseKeyAccountActionRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public Microsoft.Xrm.Sdk.EntityReference Target
		{
			get
			{
				if (this.Parameters.Contains("Target"))
				{
					return ((Microsoft.Xrm.Sdk.EntityReference)(this.Parameters["Target"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityReference);
				}
			}
			set
			{
				this.Parameters["Target"] = value;
			}
		}
		
		public new_ReviseKeyAccountActionRequest()
		{
			this.RequestName = "new_ReviseKeyAccountAction";
			this.Target = default(Microsoft.Xrm.Sdk.EntityReference);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("new_ReviseKeyAccountAction")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9479")]
	public partial class new_ReviseKeyAccountActionResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public new_ReviseKeyAccountActionResponse()
		{
		}
		
		public Microsoft.Xrm.Sdk.EntityReference KeyAccountID
		{
			get
			{
				if (this.Results.Contains("KeyAccountID"))
				{
					return ((Microsoft.Xrm.Sdk.EntityReference)(this.Results["KeyAccountID"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityReference);
				}
			}
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/rent/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("rent_AGITQuoteProductAssignToBC")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9479")]
	public partial class rent_AGITQuoteProductAssignToBCRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public string UserBC
		{
			get
			{
				if (this.Parameters.Contains("UserBC"))
				{
					return ((string)(this.Parameters["UserBC"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["UserBC"] = value;
			}
		}
		
		public string RecordID
		{
			get
			{
				if (this.Parameters.Contains("RecordID"))
				{
					return ((string)(this.Parameters["RecordID"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["RecordID"] = value;
			}
		}
		
		public Microsoft.Xrm.Sdk.EntityReference Target
		{
			get
			{
				if (this.Parameters.Contains("Target"))
				{
					return ((Microsoft.Xrm.Sdk.EntityReference)(this.Parameters["Target"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityReference);
				}
			}
			set
			{
				this.Parameters["Target"] = value;
			}
		}
		
		public rent_AGITQuoteProductAssignToBCRequest()
		{
			this.RequestName = "rent_AGITQuoteProductAssignToBC";
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/rent/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("rent_AGITQuoteProductAssignToBC")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9479")]
	public partial class rent_AGITQuoteProductAssignToBCResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public rent_AGITQuoteProductAssignToBCResponse()
		{
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("new_AGITKeyAccountGenerateMasterMarketSizeFromKeyAccount")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9479")]
	public partial class new_AGITKeyAccountGenerateMasterMarketSizeFromKeyAccountRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public string RecordID
		{
			get
			{
				if (this.Parameters.Contains("RecordID"))
				{
					return ((string)(this.Parameters["RecordID"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["RecordID"] = value;
			}
		}
		
		public Microsoft.Xrm.Sdk.EntityReference Target
		{
			get
			{
				if (this.Parameters.Contains("Target"))
				{
					return ((Microsoft.Xrm.Sdk.EntityReference)(this.Parameters["Target"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityReference);
				}
			}
			set
			{
				this.Parameters["Target"] = value;
			}
		}
		
		public new_AGITKeyAccountGenerateMasterMarketSizeFromKeyAccountRequest()
		{
			this.RequestName = "new_AGITKeyAccountGenerateMasterMarketSizeFromKeyAccount";
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("new_AGITKeyAccountGenerateMasterMarketSizeFromKeyAccount")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9479")]
	public partial class new_AGITKeyAccountGenerateMasterMarketSizeFromKeyAccountResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public new_AGITKeyAccountGenerateMasterMarketSizeFromKeyAccountResponse()
		{
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("new_AGITMarketSizeActionGenerateMarketSizeResultPSS")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9479")]
	public partial class new_AGITMarketSizeActionGenerateMarketSizeResultPSSRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public Microsoft.Xrm.Sdk.EntityReference Target
		{
			get
			{
				if (this.Parameters.Contains("Target"))
				{
					return ((Microsoft.Xrm.Sdk.EntityReference)(this.Parameters["Target"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityReference);
				}
			}
			set
			{
				this.Parameters["Target"] = value;
			}
		}
		
		public new_AGITMarketSizeActionGenerateMarketSizeResultPSSRequest()
		{
			this.RequestName = "new_AGITMarketSizeActionGenerateMarketSizeResultPSS";
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("new_AGITMarketSizeActionGenerateMarketSizeResultPSS")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9479")]
	public partial class new_AGITMarketSizeActionGenerateMarketSizeResultPSSResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public new_AGITMarketSizeActionGenerateMarketSizeResultPSSResponse()
		{
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("new_AGITMarketSizeActionGenerateMasterMarketSizeSublines")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9479")]
	public partial class new_AGITMarketSizeActionGenerateMasterMarketSizeSublinesRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public Microsoft.Xrm.Sdk.EntityReference Target
		{
			get
			{
				if (this.Parameters.Contains("Target"))
				{
					return ((Microsoft.Xrm.Sdk.EntityReference)(this.Parameters["Target"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityReference);
				}
			}
			set
			{
				this.Parameters["Target"] = value;
			}
		}
		
		public new_AGITMarketSizeActionGenerateMasterMarketSizeSublinesRequest()
		{
			this.RequestName = "new_AGITMarketSizeActionGenerateMasterMarketSizeSublines";
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("new_AGITMarketSizeActionGenerateMasterMarketSizeSublines")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9479")]
	public partial class new_AGITMarketSizeActionGenerateMasterMarketSizeSublinesResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public new_AGITMarketSizeActionGenerateMasterMarketSizeSublinesResponse()
		{
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/tss/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("tss_AGITMarketSizeActionGenerateMSHeader")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9479")]
	public partial class tss_AGITMarketSizeActionGenerateMSHeaderRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public string RecordID
		{
			get
			{
				if (this.Parameters.Contains("RecordID"))
				{
					return ((string)(this.Parameters["RecordID"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["RecordID"] = value;
			}
		}
		
		public Microsoft.Xrm.Sdk.EntityReference Target
		{
			get
			{
				if (this.Parameters.Contains("Target"))
				{
					return ((Microsoft.Xrm.Sdk.EntityReference)(this.Parameters["Target"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityReference);
				}
			}
			set
			{
				this.Parameters["Target"] = value;
			}
		}
		
		public tss_AGITMarketSizeActionGenerateMSHeaderRequest()
		{
			this.RequestName = "tss_AGITMarketSizeActionGenerateMSHeader";
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/tss/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("tss_AGITMarketSizeActionGenerateMSHeader")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9479")]
	public partial class tss_AGITMarketSizeActionGenerateMSHeaderResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public tss_AGITMarketSizeActionGenerateMSHeaderResponse()
		{
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/rwb/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("rwb_CustomiseRibbon")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9479")]
	public partial class rwb_CustomiseRibbonRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public string Operation
		{
			get
			{
				if (this.Parameters.Contains("Operation"))
				{
					return ((string)(this.Parameters["Operation"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["Operation"] = value;
			}
		}
		
		public string Data
		{
			get
			{
				if (this.Parameters.Contains("Data"))
				{
					return ((string)(this.Parameters["Data"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["Data"] = value;
			}
		}
		
		public rwb_CustomiseRibbonRequest()
		{
			this.RequestName = "rwb_CustomiseRibbon";
			this.Operation = default(string);
			this.Data = default(string);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/rwb/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("rwb_CustomiseRibbon")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9479")]
	public partial class rwb_CustomiseRibbonResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public rwb_CustomiseRibbonResponse()
		{
		}
		
		public string Result
		{
			get
			{
				if (this.Results.Contains("Result"))
				{
					return ((string)(this.Results["Result"]));
				}
				else
				{
					return default(string);
				}
			}
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/dxtools/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("dxtools_SendCustomEmail")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9479")]
	public partial class dxtools_SendCustomEmailRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public string EmailTemplateName
		{
			get
			{
				if (this.Parameters.Contains("EmailTemplateName"))
				{
					return ((string)(this.Parameters["EmailTemplateName"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["EmailTemplateName"] = value;
			}
		}
		
		public Microsoft.Xrm.Sdk.EntityReference FromSender
		{
			get
			{
				if (this.Parameters.Contains("FromSender"))
				{
					return ((Microsoft.Xrm.Sdk.EntityReference)(this.Parameters["FromSender"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityReference);
				}
			}
			set
			{
				this.Parameters["FromSender"] = value;
			}
		}
		
		public Microsoft.Xrm.Sdk.EntityCollection ToRecipient
		{
			get
			{
				if (this.Parameters.Contains("ToRecipient"))
				{
					return ((Microsoft.Xrm.Sdk.EntityCollection)(this.Parameters["ToRecipient"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityCollection);
				}
			}
			set
			{
				this.Parameters["ToRecipient"] = value;
			}
		}
		
		public Microsoft.Xrm.Sdk.EntityReference Regarding
		{
			get
			{
				if (this.Parameters.Contains("Regarding"))
				{
					return ((Microsoft.Xrm.Sdk.EntityReference)(this.Parameters["Regarding"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityReference);
				}
			}
			set
			{
				this.Parameters["Regarding"] = value;
			}
		}
		
		public Microsoft.Xrm.Sdk.EntityReference RecordContext
		{
			get
			{
				if (this.Parameters.Contains("RecordContext"))
				{
					return ((Microsoft.Xrm.Sdk.EntityReference)(this.Parameters["RecordContext"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityReference);
				}
			}
			set
			{
				this.Parameters["RecordContext"] = value;
			}
		}
		
		public string Attachments
		{
			get
			{
				if (this.Parameters.Contains("Attachments"))
				{
					return ((string)(this.Parameters["Attachments"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["Attachments"] = value;
			}
		}
		
		public bool AllowDuplicateAttachments
		{
			get
			{
				if (this.Parameters.Contains("AllowDuplicateAttachments"))
				{
					return ((bool)(this.Parameters["AllowDuplicateAttachments"]));
				}
				else
				{
					return default(bool);
				}
			}
			set
			{
				this.Parameters["AllowDuplicateAttachments"] = value;
			}
		}
		
		public bool OnlyUseAttachmentsInTemplate
		{
			get
			{
				if (this.Parameters.Contains("OnlyUseAttachmentsInTemplate"))
				{
					return ((bool)(this.Parameters["OnlyUseAttachmentsInTemplate"]));
				}
				else
				{
					return default(bool);
				}
			}
			set
			{
				this.Parameters["OnlyUseAttachmentsInTemplate"] = value;
			}
		}
		
		public string StaticParameters
		{
			get
			{
				if (this.Parameters.Contains("StaticParameters"))
				{
					return ((string)(this.Parameters["StaticParameters"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["StaticParameters"] = value;
			}
		}
		
		public Microsoft.Xrm.Sdk.EntityReference Target
		{
			get
			{
				if (this.Parameters.Contains("Target"))
				{
					return ((Microsoft.Xrm.Sdk.EntityReference)(this.Parameters["Target"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityReference);
				}
			}
			set
			{
				this.Parameters["Target"] = value;
			}
		}
		
		public dxtools_SendCustomEmailRequest()
		{
			this.RequestName = "dxtools_SendCustomEmail";
			this.EmailTemplateName = default(string);
			this.FromSender = default(Microsoft.Xrm.Sdk.EntityReference);
			this.ToRecipient = default(Microsoft.Xrm.Sdk.EntityCollection);
			this.Target = default(Microsoft.Xrm.Sdk.EntityReference);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/dxtools/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("dxtools_SendCustomEmail")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9479")]
	public partial class dxtools_SendCustomEmailResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public dxtools_SendCustomEmailResponse()
		{
		}
		
		public Microsoft.Xrm.Sdk.EntityReference NewCreatedEmail
		{
			get
			{
				if (this.Results.Contains("NewCreatedEmail"))
				{
					return ((Microsoft.Xrm.Sdk.EntityReference)(this.Results["NewCreatedEmail"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityReference);
				}
			}
		}
	}
}
