// <copyright file="PreCreate_serviceappointment_checkconditiontype.cs" company="">
// Copyright (c) 2019 All Rights Reserved
// </copyright>
// <author></author>
// <date>01-Aug-19 2:46:49 PM</date>
// <summary>Implements the PreCreate_serviceappointment_checkconditiontype Plugin.</summary>
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
// </auto-generated>

using System;
using System.ServiceModel;
using Microsoft.Xrm.Sdk;
using EnhancementCRM.Plugins.Business_Layer;

namespace EnhancementCRM.Plugins
{

    /// <summary>
    /// PreCreate_serviceappointment_checkconditiontype Plugin.
    /// </summary>    
    public class PreCreate_serviceappointment_checkconditiontype: PluginBase
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PreCreate_serviceappointment_checkconditiontype"/> class.
        /// </summary>
        /// <param name="unsecure">Contains public (unsecured) configuration information.</param>
        /// <param name="secure">Contains non-public (secured) configuration information. 
        /// When using Microsoft Dynamics 365 for Outlook with Offline Access, 
        /// the secure string is not passed to a plug-in that executes while the client is offline.</param>
        public PreCreate_serviceappointment_checkconditiontype(string unsecure, string secure)
            : base(typeof(PreCreate_serviceappointment_checkconditiontype))
        {
            
           // TODO: Implement your custom configuration handling.
        }


        /// <summary>
        /// Main entry point for he business logic that the plug-in is to execute.
        /// </summary>
        /// <param name="localContext">The <see cref="LocalPluginContext"/> which contains the
        /// <see cref="IPluginExecutionContext"/>,
        /// <see cref="IOrganizationService"/>
        /// and <see cref="ITracingService"/>
        /// </param>
        /// <remarks>
        /// For improved performance, Microsoft Dynamics 365 caches plug-in instances.
        /// The plug-in's Execute method should be written to be stateless as the constructor
        /// is not called for every invocation of the plug-in. Also, multiple system threads
        /// could execute the plug-in at the same time. All per invocation state information
        /// is stored in the context. This means that you should not use global variables in plug-ins.
        /// </remarks>
        protected override void ExecuteCrmPlugin(LocalPluginContext localContext)
        {
            if (localContext == null)
            {
                throw new InvalidPluginExecutionException("localContext");
            }

            IPluginExecutionContext context = localContext.PluginExecutionContext;
            ITracingService tracer = localContext.TracingService;
            Entity entity = (Entity)context.InputParameters["Target"];

            // TODO: Implement your custom Plug-in business logic.
            BL_serviceappointment _BL_serviceappointment = new BL_serviceappointment();
            _BL_serviceappointment.PreCreate_serviceappointment_checkconditiontype(localContext.OrganizationService, localContext.PluginExecutionContext, entity, localContext.TracingService);
        }
    }
}
