//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnhancementCRM.HelperUnit.SAP_MOVING_PRICE {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", ConfigurationName="SAP_MOVING_PRICE.ZPST_FM_005_V2")]
    public interface ZPST_FM_005_V2 {
        
        // CODEGEN: Generating message contract since the operation ZPST_FM_005 is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="urn:sap-com:document:sap:rfc:functions:ZPST_FM_005_V2:ZPST_FM_005Request", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        EnhancementCRM.HelperUnit.SAP_MOVING_PRICE.ZPST_FM_005Response1 ZPST_FM_005(EnhancementCRM.HelperUnit.SAP_MOVING_PRICE.ZPST_FM_005Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:sap-com:document:sap:rfc:functions:ZPST_FM_005_V2:ZPST_FM_005Request", ReplyAction="*")]
        System.Threading.Tasks.Task<EnhancementCRM.HelperUnit.SAP_MOVING_PRICE.ZPST_FM_005Response1> ZPST_FM_005Async(EnhancementCRM.HelperUnit.SAP_MOVING_PRICE.ZPST_FM_005Request request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZPST_FM_005 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string cSRF_TOKENField;
        
        private string mATERIALField;
        
        private string pLANTField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string CSRF_TOKEN {
            get {
                return this.cSRF_TOKENField;
            }
            set {
                this.cSRF_TOKENField = value;
                this.RaisePropertyChanged("CSRF_TOKEN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string MATERIAL {
            get {
                return this.mATERIALField;
            }
            set {
                this.mATERIALField = value;
                this.RaisePropertyChanged("MATERIAL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string PLANT {
            get {
                return this.pLANTField;
            }
            set {
                this.pLANTField = value;
                this.RaisePropertyChanged("PLANT");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZPST_FM_005Response : object, System.ComponentModel.INotifyPropertyChanged {
        
        private decimal mOVING_PRICEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public decimal MOVING_PRICE {
            get {
                return this.mOVING_PRICEField;
            }
            set {
                this.mOVING_PRICEField = value;
                this.RaisePropertyChanged("MOVING_PRICE");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZPST_FM_005Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public EnhancementCRM.HelperUnit.SAP_MOVING_PRICE.ZPST_FM_005 ZPST_FM_005;
        
        public ZPST_FM_005Request() {
        }
        
        public ZPST_FM_005Request(EnhancementCRM.HelperUnit.SAP_MOVING_PRICE.ZPST_FM_005 ZPST_FM_005) {
            this.ZPST_FM_005 = ZPST_FM_005;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZPST_FM_005Response1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public EnhancementCRM.HelperUnit.SAP_MOVING_PRICE.ZPST_FM_005Response ZPST_FM_005Response;
        
        public ZPST_FM_005Response1() {
        }
        
        public ZPST_FM_005Response1(EnhancementCRM.HelperUnit.SAP_MOVING_PRICE.ZPST_FM_005Response ZPST_FM_005Response) {
            this.ZPST_FM_005Response = ZPST_FM_005Response;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ZPST_FM_005_V2Channel : EnhancementCRM.HelperUnit.SAP_MOVING_PRICE.ZPST_FM_005_V2, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ZPST_FM_005_V2Client : System.ServiceModel.ClientBase<EnhancementCRM.HelperUnit.SAP_MOVING_PRICE.ZPST_FM_005_V2>, EnhancementCRM.HelperUnit.SAP_MOVING_PRICE.ZPST_FM_005_V2 {
        
        public ZPST_FM_005_V2Client() {
        }
        
        public ZPST_FM_005_V2Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ZPST_FM_005_V2Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ZPST_FM_005_V2Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ZPST_FM_005_V2Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EnhancementCRM.HelperUnit.SAP_MOVING_PRICE.ZPST_FM_005Response1 EnhancementCRM.HelperUnit.SAP_MOVING_PRICE.ZPST_FM_005_V2.ZPST_FM_005(EnhancementCRM.HelperUnit.SAP_MOVING_PRICE.ZPST_FM_005Request request) {
            return base.Channel.ZPST_FM_005(request);
        }
        
        public EnhancementCRM.HelperUnit.SAP_MOVING_PRICE.ZPST_FM_005Response ZPST_FM_005(EnhancementCRM.HelperUnit.SAP_MOVING_PRICE.ZPST_FM_005 ZPST_FM_0051) {
            EnhancementCRM.HelperUnit.SAP_MOVING_PRICE.ZPST_FM_005Request inValue = new EnhancementCRM.HelperUnit.SAP_MOVING_PRICE.ZPST_FM_005Request();
            inValue.ZPST_FM_005 = ZPST_FM_0051;
            EnhancementCRM.HelperUnit.SAP_MOVING_PRICE.ZPST_FM_005Response1 retVal = ((EnhancementCRM.HelperUnit.SAP_MOVING_PRICE.ZPST_FM_005_V2)(this)).ZPST_FM_005(inValue);
            return retVal.ZPST_FM_005Response;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EnhancementCRM.HelperUnit.SAP_MOVING_PRICE.ZPST_FM_005Response1> EnhancementCRM.HelperUnit.SAP_MOVING_PRICE.ZPST_FM_005_V2.ZPST_FM_005Async(EnhancementCRM.HelperUnit.SAP_MOVING_PRICE.ZPST_FM_005Request request) {
            return base.Channel.ZPST_FM_005Async(request);
        }
        
        public System.Threading.Tasks.Task<EnhancementCRM.HelperUnit.SAP_MOVING_PRICE.ZPST_FM_005Response1> ZPST_FM_005Async(EnhancementCRM.HelperUnit.SAP_MOVING_PRICE.ZPST_FM_005 ZPST_FM_005) {
            EnhancementCRM.HelperUnit.SAP_MOVING_PRICE.ZPST_FM_005Request inValue = new EnhancementCRM.HelperUnit.SAP_MOVING_PRICE.ZPST_FM_005Request();
            inValue.ZPST_FM_005 = ZPST_FM_005;
            return ((EnhancementCRM.HelperUnit.SAP_MOVING_PRICE.ZPST_FM_005_V2)(this)).ZPST_FM_005Async(inValue);
        }
    }
}
