// <copyright file="PostFunctionalLocationUpdate.cs" company="">
// Copyright (c) 2014 All Rights Reserved
// </copyright>
// <author></author>
// <date>12/8/2014 11:22:10 AM</date>
// <summary>Implements the PostFunctionalLocationUpdate Plugin.</summary>
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
// </auto-generated>
namespace TrakNusRapidService.Plugins
{
    using System;
    using System.ServiceModel;
    using Microsoft.Xrm.Sdk;

    using BusinessLayer;

    /// <summary>
    /// PostFunctionalLocationUpdate Plugin.
    /// Fires when the following attributes are updated:
    /// trs_area,trs_customer,trs_frommobile,trs_functionaladdress,trs_functionalcode,trs_functionallatitude,trs_functionallocation,trs_functionallongitude,trs_name
    /// </summary>    
    public class PostFunctionalLocationUpdate: Plugin
    {
        /// <summary>
        /// Alias of the image registered for the snapshot of the 
        /// primary entity's attributes before the core platform operation executes.
        /// The image contains the following attributes:
        /// No Attributes
        /// </summary>
        private readonly string preImageAlias = "PreImage";

        /// <summary>
        /// Initializes a new instance of the <see cref="PostFunctionalLocationUpdate"/> class.
        /// </summary>
        public PostFunctionalLocationUpdate()
            : base(typeof(PostFunctionalLocationUpdate))
        {
            base.RegisteredEvents.Add(new Tuple<int, string, string, Action<LocalPluginContext>>(40, "Update", "trs_functionallocation", new Action<LocalPluginContext>(ExecutePostFunctionalLocationUpdate)));

            // Note : you can register for more events here if this plugin is not specific to an individual entity and message combination.
            // You may also need to update your RegisterFile.crmregister plug-in registration file to reflect any change.
        }

        /// <summary>
        /// Executes the plug-in.
        /// </summary>
        /// <param name="localContext">The <see cref="LocalPluginContext"/> which contains the
        /// <see cref="IPluginExecutionContext"/>,
        /// <see cref="IOrganizationService"/>
        /// and <see cref="ITracingService"/>
        /// </param>
        /// <remarks>
        /// For improved performance, Microsoft Dynamics CRM caches plug-in instances.
        /// The plug-in's Execute method should be written to be stateless as the constructor
        /// is not called for every invocation of the plug-in. Also, multiple system threads
        /// could execute the plug-in at the same time. All per invocation state information
        /// is stored in the context. This means that you should not use global variables in plug-ins.
        /// </remarks>
        protected void ExecutePostFunctionalLocationUpdate(LocalPluginContext localContext)
        {
            if (localContext == null)
            {
                throw new ArgumentNullException("localContext");
            }

            IPluginExecutionContext context = localContext.PluginExecutionContext;

            Entity preImageEntity = (context.PreEntityImages != null && context.PreEntityImages.Contains(this.preImageAlias)) ? context.PreEntityImages[this.preImageAlias] : null;

            // TODO: Implement your custom Plug-in business logic.

            BL_trs_funtionallocation _BL_trs_funcationallocation = new BL_trs_funtionallocation();
            _BL_trs_funcationallocation.Form_OnCreate(localContext.OrganizationService, localContext.PluginExecutionContext);

        }
    }
}
