// <copyright file="PostFunctionalLocationCreate.cs" company="">
// Copyright (c) 2014 All Rights Reserved
// </copyright>
// <author></author>
// <date>11/21/2014 10:51:09 AM</date>
// <summary>Implements the PostFunctionalLocationCreate Plugin.</summary>
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
// </auto-generated>
namespace TrakNusRapidService.Plugins
{
    using System;
    using System.ServiceModel;
    using Microsoft.Xrm.Sdk;

    using BusinessLayer;

    /// <summary>
    /// PostFunctionalLocationCreate Plugin.
    /// </summary>    
    public class PostFunctionalLocationCreate: Plugin
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PostFunctionalLocationCreate"/> class.
        /// </summary>
        public PostFunctionalLocationCreate()
            : base(typeof(PostFunctionalLocationCreate))
        {
            base.RegisteredEvents.Add(new Tuple<int, string, string, Action<LocalPluginContext>>(40, "Create", "trs_functionallocation", new Action<LocalPluginContext>(ExecutePostFunctionalLocationCreate)));

            // Note : you can register for more events here if this plugin is not specific to an individual entity and message combination.
            // You may also need to update your RegisterFile.crmregister plug-in registration file to reflect any change.
        }

        /// <summary>
        /// Executes the plug-in.
        /// </summary>
        /// <param name="localContext">The <see cref="LocalPluginContext"/> which contains the
        /// <see cref="IPluginExecutionContext"/>,
        /// <see cref="IOrganizationService"/>
        /// and <see cref="ITracingService"/>
        /// </param>
        /// <remarks>
        /// For improved performance, Microsoft Dynamics CRM caches plug-in instances.
        /// The plug-in's Execute method should be written to be stateless as the constructor
        /// is not called for every invocation of the plug-in. Also, multiple system threads
        /// could execute the plug-in at the same time. All per invocation state information
        /// is stored in the context. This means that you should not use global variables in plug-ins.
        /// </remarks>
        protected void ExecutePostFunctionalLocationCreate(LocalPluginContext localContext)
        {
            if (localContext == null)
            {
                throw new ArgumentNullException("localContext");
            }

            // TODO: Implement your custom Plug-in business logic.
            BL_trs_funtionallocation _BL_trs_functionallocation = new BL_trs_funtionallocation();
            _BL_trs_functionallocation.UpdateFunctionalLocationRunningNumber(localContext.OrganizationService,localContext.PluginExecutionContext);
            _BL_trs_functionallocation.Form_OnCreate(localContext.OrganizationService, localContext.PluginExecutionContext);
        }
    }
}
