// <copyright file="PreValidatePopulationCreate.cs" company="">
// Copyright (c) 2014 All Rights Reserved
// </copyright>
// <author></author>
// <date>11/7/2014 11:26:19 AM</date>
// <summary>Implements the PreValidatePopulationCreate Plugin.</summary>
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
// </auto-generated>
namespace TrakNusRapidService.Plugins
{
    using System;
    using System.ServiceModel;
    using Microsoft.Xrm.Sdk;
    using TrakNusRapidService.Plugins.BusinessLayer;

    /// <summary>
    /// PreValidatePopulationCreate Plugin.
    /// </summary>    
    public class PreValidatePopulationCreate: Plugin
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PreValidatePopulationCreate"/> class.
        /// </summary>
        public PreValidatePopulationCreate()
            : base(typeof(PreValidatePopulationCreate))
        {
            base.RegisteredEvents.Add(new Tuple<int, string, string, Action<LocalPluginContext>>(10, "Create", "new_population", new Action<LocalPluginContext>(ExecutePreValidatePopulationCreate)));

            // Note : you can register for more events here if this plugin is not specific to an individual entity and message combination.
            // You may also need to update your RegisterFile.crmregister plug-in registration file to reflect any change.
        }

        /// <summary>
        /// Executes the plug-in.
        /// </summary>
        /// <param name="localContext">The <see cref="LocalPluginContext"/> which contains the
        /// <see cref="IPluginExecutionContext"/>,
        /// <see cref="IOrganizationService"/>
        /// and <see cref="ITracingService"/>
        /// </param>
        /// <remarks>
        /// For improved performance, Microsoft Dynamics CRM caches plug-in instances.
        /// The plug-in's Execute method should be written to be stateless as the constructor
        /// is not called for every invocation of the plug-in. Also, multiple system threads
        /// could execute the plug-in at the same time. All per invocation state information
        /// is stored in the context. This means that you should not use global variables in plug-ins.
        /// </remarks>
        protected void ExecutePreValidatePopulationCreate(LocalPluginContext localContext)
        {
            if (localContext == null)
            {
                throw new ArgumentNullException("localContext");
            }

            BL_new_population _BL_new_population = new BL_new_population();
            _BL_new_population.Form_OnCreatePreValidate(localContext.OrganizationService, localContext.PluginExecutionContext);
        }
    }
}
