// <copyright file="PostProspectPartUpdate.cs" company="">
// Copyright (c) 2018 All Rights Reserved
// </copyright>
// <author></author>
// <date>1/12/2018 10:53:24 AM</date>
// <summary>Implements the PostProspectPartUpdate Plugin.</summary>
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
// </auto-generated>
namespace TrakNusSparepartSystem.Plugins
{
    using System;
    using System.ServiceModel;
    using Microsoft.Xrm.Sdk;
    using BusinessLayer;

    /// <summary>
    /// PostProspectPartUpdate Plugin.
    /// Fires when the following attributes are updated:
    /// tss_estimationclosedate
    /// </summary>    
    public class PostProspectPartUpdate: Plugin
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PostProspectPartUpdate"/> class.
        /// </summary>
        public PostProspectPartUpdate()
            : base(typeof(PostProspectPartUpdate))
        {
            base.RegisteredEvents.Add(new Tuple<int, string, string, Action<LocalPluginContext>>(40, "Update", "tss_prospectpartheader", new Action<LocalPluginContext>(ExecutePostProspectPartUpdate)));

            // Note : you can register for more events here if this plugin is not specific to an individual entity and message combination.
            // You may also need to update your RegisterFile.crmregister plug-in registration file to reflect any change.
        }

        /// <summary>
        /// Executes the plug-in.
        /// </summary>
        /// <param name="localContext">The <see cref="LocalPluginContext"/> which contains the
        /// <see cref="IPluginExecutionContext"/>,
        /// <see cref="IOrganizationService"/>
        /// and <see cref="ITracingService"/>
        /// </param>
        /// <remarks>
        /// For improved performance, Microsoft Dynamics CRM caches plug-in instances.
        /// The plug-in's Execute method should be written to be stateless as the constructor
        /// is not called for every invocation of the plug-in. Also, multiple system threads
        /// could execute the plug-in at the same time. All per invocation state information
        /// is stored in the context. This means that you should not use global variables in plug-ins.
        /// </remarks>
        protected void ExecutePostProspectPartUpdate(LocalPluginContext localContext)
        {
            if (localContext == null)
            {
                throw new ArgumentNullException("localContext");
            }

            // TODO: Implement your custom Plug-in business logic.
            BL_tss_prospectpartheader _BL_tss_prospectpart = new BL_tss_prospectpartheader();
            _BL_tss_prospectpart.Form_OnCreate_UpdateProspectRating(localContext.OrganizationService, localContext.PluginExecutionContext);
        }
    }
}
